/*
 * autogenerated file: describes V8 heap objects for programmatic 
 * inspection.
 */

#include "heap-dbg-common.h"
#include "heap-dbg-constants.h"

/* MaybeObject class */
v8_field_t v8_MaybeObject_fields[] = {
	{ NULL }
};

v8_class_t v8_MaybeObject_class = {
	"MaybeObject", NULL, v8_MaybeObject_fields
};

/* Relocatable class */
v8_field_t v8_Relocatable_fields[] = {
	{ NULL }
};

v8_class_t v8_Relocatable_class = {
	"Relocatable", NULL, v8_Relocatable_fields
};

/* AllStatic class */
v8_field_t v8_AllStatic_fields[] = {
	{ NULL }
};

v8_class_t v8_AllStatic_class = {
	"AllStatic", NULL, v8_AllStatic_fields
};

/* Object class */
v8_field_t v8_Object_fields[] = {
	{ NULL }
};

v8_class_t v8_Object_class = {
	"Object", &v8_MaybeObject_class, v8_Object_fields
};

/* Failure class */
v8_field_t v8_Failure_fields[] = {
	{ NULL }
};

v8_class_t v8_Failure_class = {
	"Failure", &v8_MaybeObject_class, v8_Failure_fields
};

/* FlatStringReader class */
v8_field_t v8_FlatStringReader_fields[] = {
	{ NULL }
};

v8_class_t v8_FlatStringReader_class = {
	"FlatStringReader", &v8_Relocatable_class, v8_FlatStringReader_fields
};

/* BooleanBit class */
v8_field_t v8_BooleanBit_fields[] = {
	{ NULL }
};

v8_class_t v8_BooleanBit_class = {
	"BooleanBit", &v8_AllStatic_class, v8_BooleanBit_fields
};

/* Smi class */
v8_field_t v8_Smi_fields[] = {
	{ NULL }
};

v8_class_t v8_Smi_class = {
	"Smi", &v8_Object_class, v8_Smi_fields
};

/* HeapObject class */
v8_field_t v8_HeapObject_fields[] = {
	{ "map", V8_OFF_HeapObject_map, sizeof (uintptr_t) },
	{ NULL }
};

v8_class_t v8_HeapObject_class = {
	"HeapObject", &v8_Object_class, v8_HeapObject_fields
};

/* HeapNumber class */
v8_field_t v8_HeapNumber_fields[] = {
	{ NULL }
};

v8_class_t v8_HeapNumber_class = {
	"HeapNumber", &v8_HeapObject_class, v8_HeapNumber_fields
};

/* JSObject class */
v8_field_t v8_JSObject_fields[] = {
	{ "properties", V8_OFF_JSObject_properties, sizeof (uintptr_t) },
	{ "elements", V8_OFF_JSObject_elements, sizeof (uintptr_t) },
	{ NULL }
};

v8_class_t v8_JSObject_class = {
	"JSObject", &v8_HeapObject_class, v8_JSObject_fields
};

/* FixedArray class */
v8_field_t v8_FixedArray_fields[] = {
	{ "length", V8_OFF_FixedArray_length, sizeof (uintptr_t) },
	{ NULL }
};

v8_class_t v8_FixedArray_class = {
	"FixedArray", &v8_HeapObject_class, v8_FixedArray_fields
};

/* ByteArray class */
v8_field_t v8_ByteArray_fields[] = {
	{ "length", V8_OFF_ByteArray_length, sizeof (uintptr_t) },
	{ NULL }
};

v8_class_t v8_ByteArray_class = {
	"ByteArray", &v8_HeapObject_class, v8_ByteArray_fields
};

/* PixelArray class */
v8_field_t v8_PixelArray_fields[] = {
	{ NULL }
};

v8_class_t v8_PixelArray_class = {
	"PixelArray", &v8_HeapObject_class, v8_PixelArray_fields
};

/* ExternalArray class */
v8_field_t v8_ExternalArray_fields[] = {
	{ NULL }
};

v8_class_t v8_ExternalArray_class = {
	"ExternalArray", &v8_HeapObject_class, v8_ExternalArray_fields
};

/* Code class */
v8_field_t v8_Code_fields[] = {
	{ "relocation_info", V8_OFF_Code_relocation_info, sizeof (uintptr_t) },
	{ "deoptimization_data", V8_OFF_Code_deoptimization_data, sizeof (uintptr_t) },
	{ NULL }
};

v8_class_t v8_Code_class = {
	"Code", &v8_HeapObject_class, v8_Code_fields
};

/* Map class */
v8_field_t v8_Map_fields[] = {
	{ "constructor", V8_OFF_Map_constructor, sizeof (uintptr_t) },
	{ "instance_descriptors", V8_OFF_Map_instance_descriptors, sizeof (uintptr_t) },
	{ "code_cache", V8_OFF_Map_code_cache, sizeof (uintptr_t) },
	{ NULL }
};

v8_class_t v8_Map_class = {
	"Map", &v8_HeapObject_class, v8_Map_fields
};

/* Struct class */
v8_field_t v8_Struct_fields[] = {
	{ NULL }
};

v8_class_t v8_Struct_class = {
	"Struct", &v8_HeapObject_class, v8_Struct_fields
};

/* SharedFunctionInfo class */
v8_field_t v8_SharedFunctionInfo_fields[] = {
	{ "name", V8_OFF_SharedFunctionInfo_name, sizeof (uintptr_t) },
	{ "construct_stub", V8_OFF_SharedFunctionInfo_construct_stub, sizeof (uintptr_t) },
	{ "instance_class_name", V8_OFF_SharedFunctionInfo_instance_class_name, sizeof (uintptr_t) },
	{ "function_data", V8_OFF_SharedFunctionInfo_function_data, sizeof (uintptr_t) },
	{ "script", V8_OFF_SharedFunctionInfo_script, sizeof (uintptr_t) },
	{ "debug_info", V8_OFF_SharedFunctionInfo_debug_info, sizeof (uintptr_t) },
	{ "inferred_name", V8_OFF_SharedFunctionInfo_inferred_name, sizeof (uintptr_t) },
	{ "initial_map", V8_OFF_SharedFunctionInfo_initial_map, sizeof (uintptr_t) },
	{ "this_property_assignments", V8_OFF_SharedFunctionInfo_this_property_assignments, sizeof (uintptr_t) },
	{ "length", V8_OFF_SharedFunctionInfo_length, sizeof (uintptr_t) },
	{ "formal_parameter_count", V8_OFF_SharedFunctionInfo_formal_parameter_count, sizeof (uintptr_t) },
	{ "expected_nof_properties", V8_OFF_SharedFunctionInfo_expected_nof_properties, sizeof (uintptr_t) },
	{ "num_literals", V8_OFF_SharedFunctionInfo_num_literals, sizeof (uintptr_t) },
	{ "start_position_and_type", V8_OFF_SharedFunctionInfo_start_position_and_type, sizeof (uintptr_t) },
	{ "end_position", V8_OFF_SharedFunctionInfo_end_position, sizeof (uintptr_t) },
	{ "function_token_position", V8_OFF_SharedFunctionInfo_function_token_position, sizeof (uintptr_t) },
	{ "compiler_hints", V8_OFF_SharedFunctionInfo_compiler_hints, sizeof (uintptr_t) },
	{ "this_property_assignments_count", V8_OFF_SharedFunctionInfo_this_property_assignments_count, sizeof (uintptr_t) },
	{ "opt_count", V8_OFF_SharedFunctionInfo_opt_count, sizeof (uintptr_t) },
	{ NULL }
};

v8_class_t v8_SharedFunctionInfo_class = {
	"SharedFunctionInfo", &v8_HeapObject_class, v8_SharedFunctionInfo_fields
};

/* String class */
v8_field_t v8_String_fields[] = {
	{ "length", V8_OFF_String_length, sizeof (uintptr_t) },
	{ NULL }
};

v8_class_t v8_String_class = {
	"String", &v8_HeapObject_class, v8_String_fields
};

/* Oddball class */
v8_field_t v8_Oddball_fields[] = {
	{ "to_string", V8_OFF_Oddball_to_string, sizeof (uintptr_t) },
	{ "to_number", V8_OFF_Oddball_to_number, sizeof (uintptr_t) },
	{ NULL }
};

v8_class_t v8_Oddball_class = {
	"Oddball", &v8_HeapObject_class, v8_Oddball_fields
};

/* JSGlobalPropertyCell class */
v8_field_t v8_JSGlobalPropertyCell_fields[] = {
	{ NULL }
};

v8_class_t v8_JSGlobalPropertyCell_class = {
	"JSGlobalPropertyCell", &v8_HeapObject_class, v8_JSGlobalPropertyCell_fields
};

/* Proxy class */
v8_field_t v8_Proxy_fields[] = {
	{ NULL }
};

v8_class_t v8_Proxy_class = {
	"Proxy", &v8_HeapObject_class, v8_Proxy_fields
};

/* DescriptorArray class */
v8_field_t v8_DescriptorArray_fields[] = {
	{ NULL }
};

v8_class_t v8_DescriptorArray_class = {
	"DescriptorArray", &v8_FixedArray_class, v8_DescriptorArray_fields
};

/* HashTable class */
v8_field_t v8_HashTable_fields[] = {
	{ NULL }
};

v8_class_t v8_HashTable_class = {
	"HashTable", &v8_FixedArray_class, v8_HashTable_fields
};

/* JSFunctionResultCache class */
v8_field_t v8_JSFunctionResultCache_fields[] = {
	{ NULL }
};

v8_class_t v8_JSFunctionResultCache_class = {
	"JSFunctionResultCache", &v8_FixedArray_class, v8_JSFunctionResultCache_fields
};

/* NormalizedMapCache class */
v8_field_t v8_NormalizedMapCache_fields[] = {
	{ NULL }
};

v8_class_t v8_NormalizedMapCache_class = {
	"NormalizedMapCache", &v8_FixedArray_class, v8_NormalizedMapCache_fields
};

/* ExternalByteArray class */
v8_field_t v8_ExternalByteArray_fields[] = {
	{ NULL }
};

v8_class_t v8_ExternalByteArray_class = {
	"ExternalByteArray", &v8_ExternalArray_class, v8_ExternalByteArray_fields
};

/* ExternalUnsignedByteArray class */
v8_field_t v8_ExternalUnsignedByteArray_fields[] = {
	{ NULL }
};

v8_class_t v8_ExternalUnsignedByteArray_class = {
	"ExternalUnsignedByteArray", &v8_ExternalArray_class, v8_ExternalUnsignedByteArray_fields
};

/* ExternalShortArray class */
v8_field_t v8_ExternalShortArray_fields[] = {
	{ NULL }
};

v8_class_t v8_ExternalShortArray_class = {
	"ExternalShortArray", &v8_ExternalArray_class, v8_ExternalShortArray_fields
};

/* ExternalUnsignedShortArray class */
v8_field_t v8_ExternalUnsignedShortArray_fields[] = {
	{ NULL }
};

v8_class_t v8_ExternalUnsignedShortArray_class = {
	"ExternalUnsignedShortArray", &v8_ExternalArray_class, v8_ExternalUnsignedShortArray_fields
};

/* ExternalIntArray class */
v8_field_t v8_ExternalIntArray_fields[] = {
	{ NULL }
};

v8_class_t v8_ExternalIntArray_class = {
	"ExternalIntArray", &v8_ExternalArray_class, v8_ExternalIntArray_fields
};

/* ExternalUnsignedIntArray class */
v8_field_t v8_ExternalUnsignedIntArray_fields[] = {
	{ NULL }
};

v8_class_t v8_ExternalUnsignedIntArray_class = {
	"ExternalUnsignedIntArray", &v8_ExternalArray_class, v8_ExternalUnsignedIntArray_fields
};

/* ExternalFloatArray class */
v8_field_t v8_ExternalFloatArray_fields[] = {
	{ NULL }
};

v8_class_t v8_ExternalFloatArray_class = {
	"ExternalFloatArray", &v8_ExternalArray_class, v8_ExternalFloatArray_fields
};

/* DeoptimizationInputData class */
v8_field_t v8_DeoptimizationInputData_fields[] = {
	{ NULL }
};

v8_class_t v8_DeoptimizationInputData_class = {
	"DeoptimizationInputData", &v8_FixedArray_class, v8_DeoptimizationInputData_fields
};

/* DeoptimizationOutputData class */
v8_field_t v8_DeoptimizationOutputData_fields[] = {
	{ NULL }
};

v8_class_t v8_DeoptimizationOutputData_class = {
	"DeoptimizationOutputData", &v8_FixedArray_class, v8_DeoptimizationOutputData_fields
};

/* Script class */
v8_field_t v8_Script_fields[] = {
	{ "source", V8_OFF_Script_source, sizeof (uintptr_t) },
	{ "name", V8_OFF_Script_name, sizeof (uintptr_t) },
	{ "line_offset", V8_OFF_Script_line_offset, sizeof (uintptr_t) },
	{ "column_offset", V8_OFF_Script_column_offset, sizeof (uintptr_t) },
	{ "data", V8_OFF_Script_data, sizeof (uintptr_t) },
	{ "context_data", V8_OFF_Script_context_data, sizeof (uintptr_t) },
	{ "wrapper", V8_OFF_Script_wrapper, sizeof (uintptr_t) },
	{ "type", V8_OFF_Script_type, sizeof (uintptr_t) },
	{ "compilation_type", V8_OFF_Script_compilation_type, sizeof (uintptr_t) },
	{ "line_ends", V8_OFF_Script_line_ends, sizeof (uintptr_t) },
	{ "id", V8_OFF_Script_id, sizeof (uintptr_t) },
	{ "eval_from_shared", V8_OFF_Script_eval_from_shared, sizeof (uintptr_t) },
	{ "eval_from_instructions_offset", V8_OFF_Script_eval_from_instructions_offset, sizeof (uintptr_t) },
	{ NULL }
};

v8_class_t v8_Script_class = {
	"Script", &v8_Struct_class, v8_Script_fields
};

/* JSFunction class */
v8_field_t v8_JSFunction_fields[] = {
	{ "prototype_or_initial_map", V8_OFF_JSFunction_prototype_or_initial_map, sizeof (uintptr_t) },
	{ "shared", V8_OFF_JSFunction_shared, sizeof (uintptr_t) },
	{ "literals", V8_OFF_JSFunction_literals, sizeof (uintptr_t) },
	{ "next_function_link", V8_OFF_JSFunction_next_function_link, sizeof (uintptr_t) },
	{ NULL }
};

v8_class_t v8_JSFunction_class = {
	"JSFunction", &v8_JSObject_class, v8_JSFunction_fields
};

/* JSGlobalProxy class */
v8_field_t v8_JSGlobalProxy_fields[] = {
	{ "context", V8_OFF_JSGlobalProxy_context, sizeof (uintptr_t) },
	{ NULL }
};

v8_class_t v8_JSGlobalProxy_class = {
	"JSGlobalProxy", &v8_JSObject_class, v8_JSGlobalProxy_fields
};

/* GlobalObject class */
v8_field_t v8_GlobalObject_fields[] = {
	{ "builtins", V8_OFF_GlobalObject_builtins, sizeof (uintptr_t) },
	{ "global_context", V8_OFF_GlobalObject_global_context, sizeof (uintptr_t) },
	{ "global_receiver", V8_OFF_GlobalObject_global_receiver, sizeof (uintptr_t) },
	{ NULL }
};

v8_class_t v8_GlobalObject_class = {
	"GlobalObject", &v8_JSObject_class, v8_GlobalObject_fields
};

/* JSValue class */
v8_field_t v8_JSValue_fields[] = {
	{ "value", V8_OFF_JSValue_value, sizeof (uintptr_t) },
	{ NULL }
};

v8_class_t v8_JSValue_class = {
	"JSValue", &v8_JSObject_class, v8_JSValue_fields
};

/* JSMessageObject class */
v8_field_t v8_JSMessageObject_fields[] = {
	{ "type", V8_OFF_JSMessageObject_type, sizeof (uintptr_t) },
	{ "arguments", V8_OFF_JSMessageObject_arguments, sizeof (uintptr_t) },
	{ "script", V8_OFF_JSMessageObject_script, sizeof (uintptr_t) },
	{ "stack_trace", V8_OFF_JSMessageObject_stack_trace, sizeof (uintptr_t) },
	{ "stack_frames", V8_OFF_JSMessageObject_stack_frames, sizeof (uintptr_t) },
	{ "start_position", V8_OFF_JSMessageObject_start_position, sizeof (uintptr_t) },
	{ "end_position", V8_OFF_JSMessageObject_end_position, sizeof (uintptr_t) },
	{ NULL }
};

v8_class_t v8_JSMessageObject_class = {
	"JSMessageObject", &v8_JSObject_class, v8_JSMessageObject_fields
};

/* JSRegExp class */
v8_field_t v8_JSRegExp_fields[] = {
	{ "data", V8_OFF_JSRegExp_data, sizeof (uintptr_t) },
	{ NULL }
};

v8_class_t v8_JSRegExp_class = {
	"JSRegExp", &v8_JSObject_class, v8_JSRegExp_fields
};

/* CodeCache class */
v8_field_t v8_CodeCache_fields[] = {
	{ "default_cache", V8_OFF_CodeCache_default_cache, sizeof (uintptr_t) },
	{ "normal_type_cache", V8_OFF_CodeCache_normal_type_cache, sizeof (uintptr_t) },
	{ NULL }
};

v8_class_t v8_CodeCache_class = {
	"CodeCache", &v8_Struct_class, v8_CodeCache_fields
};

/* SeqString class */
v8_field_t v8_SeqString_fields[] = {
	{ NULL }
};

v8_class_t v8_SeqString_class = {
	"SeqString", &v8_String_class, v8_SeqString_fields
};

/* ConsString class */
v8_field_t v8_ConsString_fields[] = {
	{ NULL }
};

v8_class_t v8_ConsString_class = {
	"ConsString", &v8_String_class, v8_ConsString_fields
};

/* ExternalString class */
v8_field_t v8_ExternalString_fields[] = {
	{ NULL }
};

v8_class_t v8_ExternalString_class = {
	"ExternalString", &v8_String_class, v8_ExternalString_fields
};

/* JSArray class */
v8_field_t v8_JSArray_fields[] = {
	{ "length", V8_OFF_JSArray_length, sizeof (uintptr_t) },
	{ NULL }
};

v8_class_t v8_JSArray_class = {
	"JSArray", &v8_JSObject_class, v8_JSArray_fields
};

/* AccessorInfo class */
v8_field_t v8_AccessorInfo_fields[] = {
	{ "getter", V8_OFF_AccessorInfo_getter, sizeof (uintptr_t) },
	{ "setter", V8_OFF_AccessorInfo_setter, sizeof (uintptr_t) },
	{ "data", V8_OFF_AccessorInfo_data, sizeof (uintptr_t) },
	{ "name", V8_OFF_AccessorInfo_name, sizeof (uintptr_t) },
	{ "flag", V8_OFF_AccessorInfo_flag, sizeof (uintptr_t) },
	{ NULL }
};

v8_class_t v8_AccessorInfo_class = {
	"AccessorInfo", &v8_Struct_class, v8_AccessorInfo_fields
};

/* AccessCheckInfo class */
v8_field_t v8_AccessCheckInfo_fields[] = {
	{ "named_callback", V8_OFF_AccessCheckInfo_named_callback, sizeof (uintptr_t) },
	{ "indexed_callback", V8_OFF_AccessCheckInfo_indexed_callback, sizeof (uintptr_t) },
	{ "data", V8_OFF_AccessCheckInfo_data, sizeof (uintptr_t) },
	{ NULL }
};

v8_class_t v8_AccessCheckInfo_class = {
	"AccessCheckInfo", &v8_Struct_class, v8_AccessCheckInfo_fields
};

/* InterceptorInfo class */
v8_field_t v8_InterceptorInfo_fields[] = {
	{ "getter", V8_OFF_InterceptorInfo_getter, sizeof (uintptr_t) },
	{ "setter", V8_OFF_InterceptorInfo_setter, sizeof (uintptr_t) },
	{ "query", V8_OFF_InterceptorInfo_query, sizeof (uintptr_t) },
	{ "deleter", V8_OFF_InterceptorInfo_deleter, sizeof (uintptr_t) },
	{ "enumerator", V8_OFF_InterceptorInfo_enumerator, sizeof (uintptr_t) },
	{ "data", V8_OFF_InterceptorInfo_data, sizeof (uintptr_t) },
	{ NULL }
};

v8_class_t v8_InterceptorInfo_class = {
	"InterceptorInfo", &v8_Struct_class, v8_InterceptorInfo_fields
};

/* CallHandlerInfo class */
v8_field_t v8_CallHandlerInfo_fields[] = {
	{ "callback", V8_OFF_CallHandlerInfo_callback, sizeof (uintptr_t) },
	{ "data", V8_OFF_CallHandlerInfo_data, sizeof (uintptr_t) },
	{ NULL }
};

v8_class_t v8_CallHandlerInfo_class = {
	"CallHandlerInfo", &v8_Struct_class, v8_CallHandlerInfo_fields
};

/* TemplateInfo class */
v8_field_t v8_TemplateInfo_fields[] = {
	{ "tag", V8_OFF_TemplateInfo_tag, sizeof (uintptr_t) },
	{ "property_list", V8_OFF_TemplateInfo_property_list, sizeof (uintptr_t) },
	{ NULL }
};

v8_class_t v8_TemplateInfo_class = {
	"TemplateInfo", &v8_Struct_class, v8_TemplateInfo_fields
};

/* SignatureInfo class */
v8_field_t v8_SignatureInfo_fields[] = {
	{ "receiver", V8_OFF_SignatureInfo_receiver, sizeof (uintptr_t) },
	{ "args", V8_OFF_SignatureInfo_args, sizeof (uintptr_t) },
	{ NULL }
};

v8_class_t v8_SignatureInfo_class = {
	"SignatureInfo", &v8_Struct_class, v8_SignatureInfo_fields
};

/* TypeSwitchInfo class */
v8_field_t v8_TypeSwitchInfo_fields[] = {
	{ "types", V8_OFF_TypeSwitchInfo_types, sizeof (uintptr_t) },
	{ NULL }
};

v8_class_t v8_TypeSwitchInfo_class = {
	"TypeSwitchInfo", &v8_Struct_class, v8_TypeSwitchInfo_fields
};

/* DebugInfo class */
v8_field_t v8_DebugInfo_fields[] = {
	{ "shared", V8_OFF_DebugInfo_shared, sizeof (uintptr_t) },
	{ "original_code", V8_OFF_DebugInfo_original_code, sizeof (uintptr_t) },
	{ "code", V8_OFF_DebugInfo_code, sizeof (uintptr_t) },
	{ "break_points", V8_OFF_DebugInfo_break_points, sizeof (uintptr_t) },
	{ NULL }
};

v8_class_t v8_DebugInfo_class = {
	"DebugInfo", &v8_Struct_class, v8_DebugInfo_fields
};

/* BreakPointInfo class */
v8_field_t v8_BreakPointInfo_fields[] = {
	{ "code_position", V8_OFF_BreakPointInfo_code_position, sizeof (uintptr_t) },
	{ "source_position", V8_OFF_BreakPointInfo_source_position, sizeof (uintptr_t) },
	{ "statement_position", V8_OFF_BreakPointInfo_statement_position, sizeof (uintptr_t) },
	{ "break_point_objects", V8_OFF_BreakPointInfo_break_point_objects, sizeof (uintptr_t) },
	{ NULL }
};

v8_class_t v8_BreakPointInfo_class = {
	"BreakPointInfo", &v8_Struct_class, v8_BreakPointInfo_fields
};

/* JSGlobalObject class */
v8_field_t v8_JSGlobalObject_fields[] = {
	{ NULL }
};

v8_class_t v8_JSGlobalObject_class = {
	"JSGlobalObject", &v8_GlobalObject_class, v8_JSGlobalObject_fields
};

/* JSBuiltinsObject class */
v8_field_t v8_JSBuiltinsObject_fields[] = {
	{ NULL }
};

v8_class_t v8_JSBuiltinsObject_class = {
	"JSBuiltinsObject", &v8_GlobalObject_class, v8_JSBuiltinsObject_fields
};

/* SeqAsciiString class */
v8_field_t v8_SeqAsciiString_fields[] = {
	{ NULL }
};

v8_class_t v8_SeqAsciiString_class = {
	"SeqAsciiString", &v8_SeqString_class, v8_SeqAsciiString_fields
};

/* SeqTwoByteString class */
v8_field_t v8_SeqTwoByteString_fields[] = {
	{ NULL }
};

v8_class_t v8_SeqTwoByteString_class = {
	"SeqTwoByteString", &v8_SeqString_class, v8_SeqTwoByteString_fields
};

/* ExternalAsciiString class */
v8_field_t v8_ExternalAsciiString_fields[] = {
	{ NULL }
};

v8_class_t v8_ExternalAsciiString_class = {
	"ExternalAsciiString", &v8_ExternalString_class, v8_ExternalAsciiString_fields
};

/* ExternalTwoByteString class */
v8_field_t v8_ExternalTwoByteString_fields[] = {
	{ NULL }
};

v8_class_t v8_ExternalTwoByteString_class = {
	"ExternalTwoByteString", &v8_ExternalString_class, v8_ExternalTwoByteString_fields
};

/* JSRegExpResult class */
v8_field_t v8_JSRegExpResult_fields[] = {
	{ NULL }
};

v8_class_t v8_JSRegExpResult_class = {
	"JSRegExpResult", &v8_JSArray_class, v8_JSRegExpResult_fields
};

/* FunctionTemplateInfo class */
v8_field_t v8_FunctionTemplateInfo_fields[] = {
	{ "serial_number", V8_OFF_FunctionTemplateInfo_serial_number, sizeof (uintptr_t) },
	{ "call_code", V8_OFF_FunctionTemplateInfo_call_code, sizeof (uintptr_t) },
	{ "property_accessors", V8_OFF_FunctionTemplateInfo_property_accessors, sizeof (uintptr_t) },
	{ "prototype_template", V8_OFF_FunctionTemplateInfo_prototype_template, sizeof (uintptr_t) },
	{ "parent_template", V8_OFF_FunctionTemplateInfo_parent_template, sizeof (uintptr_t) },
	{ "named_property_handler", V8_OFF_FunctionTemplateInfo_named_property_handler, sizeof (uintptr_t) },
	{ "indexed_property_handler", V8_OFF_FunctionTemplateInfo_indexed_property_handler, sizeof (uintptr_t) },
	{ "instance_template", V8_OFF_FunctionTemplateInfo_instance_template, sizeof (uintptr_t) },
	{ "class_name", V8_OFF_FunctionTemplateInfo_class_name, sizeof (uintptr_t) },
	{ "signature", V8_OFF_FunctionTemplateInfo_signature, sizeof (uintptr_t) },
	{ "instance_call_handler", V8_OFF_FunctionTemplateInfo_instance_call_handler, sizeof (uintptr_t) },
	{ "access_check_info", V8_OFF_FunctionTemplateInfo_access_check_info, sizeof (uintptr_t) },
	{ "flag", V8_OFF_FunctionTemplateInfo_flag, sizeof (uintptr_t) },
	{ NULL }
};

v8_class_t v8_FunctionTemplateInfo_class = {
	"FunctionTemplateInfo", &v8_TemplateInfo_class, v8_FunctionTemplateInfo_fields
};

/* ObjectTemplateInfo class */
v8_field_t v8_ObjectTemplateInfo_fields[] = {
	{ "constructor", V8_OFF_ObjectTemplateInfo_constructor, sizeof (uintptr_t) },
	{ "internal_field_count", V8_OFF_ObjectTemplateInfo_internal_field_count, sizeof (uintptr_t) },
	{ NULL }
};

v8_class_t v8_ObjectTemplateInfo_class = {
	"ObjectTemplateInfo", &v8_TemplateInfo_class, v8_ObjectTemplateInfo_fields
};


v8_class_t *v8_classes[] = {
	&v8_MaybeObject_class,
	&v8_Relocatable_class,
	&v8_AllStatic_class,
	&v8_Object_class,
	&v8_Failure_class,
	&v8_FlatStringReader_class,
	&v8_BooleanBit_class,
	&v8_Smi_class,
	&v8_HeapObject_class,
	&v8_HeapNumber_class,
	&v8_JSObject_class,
	&v8_FixedArray_class,
	&v8_ByteArray_class,
	&v8_PixelArray_class,
	&v8_ExternalArray_class,
	&v8_Code_class,
	&v8_Map_class,
	&v8_Struct_class,
	&v8_SharedFunctionInfo_class,
	&v8_String_class,
	&v8_Oddball_class,
	&v8_JSGlobalPropertyCell_class,
	&v8_Proxy_class,
	&v8_DescriptorArray_class,
	&v8_HashTable_class,
	&v8_JSFunctionResultCache_class,
	&v8_NormalizedMapCache_class,
	&v8_ExternalByteArray_class,
	&v8_ExternalUnsignedByteArray_class,
	&v8_ExternalShortArray_class,
	&v8_ExternalUnsignedShortArray_class,
	&v8_ExternalIntArray_class,
	&v8_ExternalUnsignedIntArray_class,
	&v8_ExternalFloatArray_class,
	&v8_DeoptimizationInputData_class,
	&v8_DeoptimizationOutputData_class,
	&v8_Script_class,
	&v8_JSFunction_class,
	&v8_JSGlobalProxy_class,
	&v8_GlobalObject_class,
	&v8_JSValue_class,
	&v8_JSMessageObject_class,
	&v8_JSRegExp_class,
	&v8_CodeCache_class,
	&v8_SeqString_class,
	&v8_ConsString_class,
	&v8_ExternalString_class,
	&v8_JSArray_class,
	&v8_AccessorInfo_class,
	&v8_AccessCheckInfo_class,
	&v8_InterceptorInfo_class,
	&v8_CallHandlerInfo_class,
	&v8_TemplateInfo_class,
	&v8_SignatureInfo_class,
	&v8_TypeSwitchInfo_class,
	&v8_DebugInfo_class,
	&v8_BreakPointInfo_class,
	&v8_JSGlobalObject_class,
	&v8_JSBuiltinsObject_class,
	&v8_SeqAsciiString_class,
	&v8_SeqTwoByteString_class,
	&v8_ExternalAsciiString_class,
	&v8_ExternalTwoByteString_class,
	&v8_JSRegExpResult_class,
	&v8_FunctionTemplateInfo_class,
	&v8_ObjectTemplateInfo_class,
};

static const int v8_nclasses = sizeof (v8_classes) / sizeof (v8_classes[0]);

