/*
 * autogenerated file: describes V8 heap objects for programmatic 
 * inspection.
 */

#include "heap-dbg-common.h"
#include "heap-dbg-constants.h"

/* MaybeObject class */
v8_field_t v8_MaybeObject_fields[] = {
	{ NULL }
};

v8_class_t v8_MaybeObject_class = {
	"MaybeObject", NULL, v8_MaybeObject_fields
};

/* Relocatable class */
v8_field_t v8_Relocatable_fields[] = {
	{ NULL }
};

v8_class_t v8_Relocatable_class = {
	"Relocatable", NULL, v8_Relocatable_fields
};

/* AllStatic class */
v8_field_t v8_AllStatic_fields[] = {
	{ NULL }
};

v8_class_t v8_AllStatic_class = {
	"AllStatic", NULL, v8_AllStatic_fields
};

/* Object class */
v8_field_t v8_Object_fields[] = {
	{ NULL }
};

v8_class_t v8_Object_class = {
	"Object", &v8_MaybeObject_class, v8_Object_fields
};

/* Failure class */
v8_field_t v8_Failure_fields[] = {
	{ NULL }
};

v8_class_t v8_Failure_class = {
	"Failure", &v8_MaybeObject_class, v8_Failure_fields
};

/* FlatStringReader class */
v8_field_t v8_FlatStringReader_fields[] = {
	{ NULL }
};

v8_class_t v8_FlatStringReader_class = {
	"FlatStringReader", &v8_Relocatable_class, v8_FlatStringReader_fields
};

/* BooleanBit class */
v8_field_t v8_BooleanBit_fields[] = {
	{ NULL }
};

v8_class_t v8_BooleanBit_class = {
	"BooleanBit", &v8_AllStatic_class, v8_BooleanBit_fields
};

/* Smi class */
v8_field_t v8_Smi_fields[] = {
	{ NULL }
};

v8_class_t v8_Smi_class = {
	"Smi", &v8_Object_class, v8_Smi_fields
};

/* HeapObject class */
v8_field_t v8_HeapObject_fields[] = {
	{ "map", V8_OFF_HEAPOBJECT_MAP, sizeof (uintptr_t) },
	{ NULL }
};

v8_class_t v8_HeapObject_class = {
	"HeapObject", &v8_Object_class, v8_HeapObject_fields
};

/* HeapNumber class */
v8_field_t v8_HeapNumber_fields[] = {
	{ NULL }
};

v8_class_t v8_HeapNumber_class = {
	"HeapNumber", &v8_HeapObject_class, v8_HeapNumber_fields
};

/* JSObject class */
v8_field_t v8_JSObject_fields[] = {
	{ "properties", V8_OFF_JSOBJECT_PROPERTIES, sizeof (uintptr_t) },
	{ "elements", V8_OFF_JSOBJECT_ELEMENTS, sizeof (uintptr_t) },
	{ NULL }
};

v8_class_t v8_JSObject_class = {
	"JSObject", &v8_HeapObject_class, v8_JSObject_fields
};

/* FixedArray class */
v8_field_t v8_FixedArray_fields[] = {
	{ "length", V8_OFF_FIXEDARRAY_LENGTH, sizeof (uintptr_t) },
	{ "data", V8_OFF_FIXEDARRAY_DATA, sizeof (uintptr_t) },
	{ NULL }
};

v8_class_t v8_FixedArray_class = {
	"FixedArray", &v8_HeapObject_class, v8_FixedArray_fields
};

/* ByteArray class */
v8_field_t v8_ByteArray_fields[] = {
	{ "length", V8_OFF_BYTEARRAY_LENGTH, sizeof (uintptr_t) },
	{ NULL }
};

v8_class_t v8_ByteArray_class = {
	"ByteArray", &v8_HeapObject_class, v8_ByteArray_fields
};

/* PixelArray class */
v8_field_t v8_PixelArray_fields[] = {
	{ NULL }
};

v8_class_t v8_PixelArray_class = {
	"PixelArray", &v8_HeapObject_class, v8_PixelArray_fields
};

/* ExternalArray class */
v8_field_t v8_ExternalArray_fields[] = {
	{ NULL }
};

v8_class_t v8_ExternalArray_class = {
	"ExternalArray", &v8_HeapObject_class, v8_ExternalArray_fields
};

/* Code class */
v8_field_t v8_Code_fields[] = {
	{ "relocation_info", V8_OFF_CODE_RELOCATION_INFO, sizeof (uintptr_t) },
	{ "deoptimization_data", V8_OFF_CODE_DEOPTIMIZATION_DATA, sizeof (uintptr_t) },
	{ NULL }
};

v8_class_t v8_Code_class = {
	"Code", &v8_HeapObject_class, v8_Code_fields
};

/* Map class */
v8_field_t v8_Map_fields[] = {
	{ "instance_attributes", V8_OFF_MAP_INSTANCE_ATTRIBUTES, sizeof (uintptr_t) },
	{ "constructor", V8_OFF_MAP_CONSTRUCTOR, sizeof (uintptr_t) },
	{ "instance_descriptors", V8_OFF_MAP_INSTANCE_DESCRIPTORS, sizeof (uintptr_t) },
	{ "code_cache", V8_OFF_MAP_CODE_CACHE, sizeof (uintptr_t) },
	{ NULL }
};

v8_class_t v8_Map_class = {
	"Map", &v8_HeapObject_class, v8_Map_fields
};

/* Struct class */
v8_field_t v8_Struct_fields[] = {
	{ NULL }
};

v8_class_t v8_Struct_class = {
	"Struct", &v8_HeapObject_class, v8_Struct_fields
};

/* SharedFunctionInfo class */
v8_field_t v8_SharedFunctionInfo_fields[] = {
	{ "name", V8_OFF_SHAREDFUNCTIONINFO_NAME, sizeof (uintptr_t) },
	{ "construct_stub", V8_OFF_SHAREDFUNCTIONINFO_CONSTRUCT_STUB, sizeof (uintptr_t) },
	{ "instance_class_name", V8_OFF_SHAREDFUNCTIONINFO_INSTANCE_CLASS_NAME, sizeof (uintptr_t) },
	{ "function_data", V8_OFF_SHAREDFUNCTIONINFO_FUNCTION_DATA, sizeof (uintptr_t) },
	{ "script", V8_OFF_SHAREDFUNCTIONINFO_SCRIPT, sizeof (uintptr_t) },
	{ "debug_info", V8_OFF_SHAREDFUNCTIONINFO_DEBUG_INFO, sizeof (uintptr_t) },
	{ "inferred_name", V8_OFF_SHAREDFUNCTIONINFO_INFERRED_NAME, sizeof (uintptr_t) },
	{ "initial_map", V8_OFF_SHAREDFUNCTIONINFO_INITIAL_MAP, sizeof (uintptr_t) },
	{ "this_property_assignments", V8_OFF_SHAREDFUNCTIONINFO_THIS_PROPERTY_ASSIGNMENTS, sizeof (uintptr_t) },
	{ "length", V8_OFF_SHAREDFUNCTIONINFO_LENGTH, sizeof (uintptr_t) },
	{ "formal_parameter_count", V8_OFF_SHAREDFUNCTIONINFO_FORMAL_PARAMETER_COUNT, sizeof (uintptr_t) },
	{ "expected_nof_properties", V8_OFF_SHAREDFUNCTIONINFO_EXPECTED_NOF_PROPERTIES, sizeof (uintptr_t) },
	{ "num_literals", V8_OFF_SHAREDFUNCTIONINFO_NUM_LITERALS, sizeof (uintptr_t) },
	{ "start_position_and_type", V8_OFF_SHAREDFUNCTIONINFO_START_POSITION_AND_TYPE, sizeof (uintptr_t) },
	{ "end_position", V8_OFF_SHAREDFUNCTIONINFO_END_POSITION, sizeof (uintptr_t) },
	{ "function_token_position", V8_OFF_SHAREDFUNCTIONINFO_FUNCTION_TOKEN_POSITION, sizeof (uintptr_t) },
	{ "compiler_hints", V8_OFF_SHAREDFUNCTIONINFO_COMPILER_HINTS, sizeof (uintptr_t) },
	{ "this_property_assignments_count", V8_OFF_SHAREDFUNCTIONINFO_THIS_PROPERTY_ASSIGNMENTS_COUNT, sizeof (uintptr_t) },
	{ "opt_count", V8_OFF_SHAREDFUNCTIONINFO_OPT_COUNT, sizeof (uintptr_t) },
	{ NULL }
};

v8_class_t v8_SharedFunctionInfo_class = {
	"SharedFunctionInfo", &v8_HeapObject_class, v8_SharedFunctionInfo_fields
};

/* String class */
v8_field_t v8_String_fields[] = {
	{ "length", V8_OFF_STRING_LENGTH, sizeof (uintptr_t) },
	{ NULL }
};

v8_class_t v8_String_class = {
	"String", &v8_HeapObject_class, v8_String_fields
};

/* Oddball class */
v8_field_t v8_Oddball_fields[] = {
	{ "to_string", V8_OFF_ODDBALL_TO_STRING, sizeof (uintptr_t) },
	{ "to_number", V8_OFF_ODDBALL_TO_NUMBER, sizeof (uintptr_t) },
	{ NULL }
};

v8_class_t v8_Oddball_class = {
	"Oddball", &v8_HeapObject_class, v8_Oddball_fields
};

/* JSGlobalPropertyCell class */
v8_field_t v8_JSGlobalPropertyCell_fields[] = {
	{ NULL }
};

v8_class_t v8_JSGlobalPropertyCell_class = {
	"JSGlobalPropertyCell", &v8_HeapObject_class, v8_JSGlobalPropertyCell_fields
};

/* Proxy class */
v8_field_t v8_Proxy_fields[] = {
	{ NULL }
};

v8_class_t v8_Proxy_class = {
	"Proxy", &v8_HeapObject_class, v8_Proxy_fields
};

/* DescriptorArray class */
v8_field_t v8_DescriptorArray_fields[] = {
	{ NULL }
};

v8_class_t v8_DescriptorArray_class = {
	"DescriptorArray", &v8_FixedArray_class, v8_DescriptorArray_fields
};

/* HashTable class */
v8_field_t v8_HashTable_fields[] = {
	{ NULL }
};

v8_class_t v8_HashTable_class = {
	"HashTable", &v8_FixedArray_class, v8_HashTable_fields
};

/* JSFunctionResultCache class */
v8_field_t v8_JSFunctionResultCache_fields[] = {
	{ NULL }
};

v8_class_t v8_JSFunctionResultCache_class = {
	"JSFunctionResultCache", &v8_FixedArray_class, v8_JSFunctionResultCache_fields
};

/* NormalizedMapCache class */
v8_field_t v8_NormalizedMapCache_fields[] = {
	{ NULL }
};

v8_class_t v8_NormalizedMapCache_class = {
	"NormalizedMapCache", &v8_FixedArray_class, v8_NormalizedMapCache_fields
};

/* ExternalByteArray class */
v8_field_t v8_ExternalByteArray_fields[] = {
	{ NULL }
};

v8_class_t v8_ExternalByteArray_class = {
	"ExternalByteArray", &v8_ExternalArray_class, v8_ExternalByteArray_fields
};

/* ExternalUnsignedByteArray class */
v8_field_t v8_ExternalUnsignedByteArray_fields[] = {
	{ NULL }
};

v8_class_t v8_ExternalUnsignedByteArray_class = {
	"ExternalUnsignedByteArray", &v8_ExternalArray_class, v8_ExternalUnsignedByteArray_fields
};

/* ExternalShortArray class */
v8_field_t v8_ExternalShortArray_fields[] = {
	{ NULL }
};

v8_class_t v8_ExternalShortArray_class = {
	"ExternalShortArray", &v8_ExternalArray_class, v8_ExternalShortArray_fields
};

/* ExternalUnsignedShortArray class */
v8_field_t v8_ExternalUnsignedShortArray_fields[] = {
	{ NULL }
};

v8_class_t v8_ExternalUnsignedShortArray_class = {
	"ExternalUnsignedShortArray", &v8_ExternalArray_class, v8_ExternalUnsignedShortArray_fields
};

/* ExternalIntArray class */
v8_field_t v8_ExternalIntArray_fields[] = {
	{ NULL }
};

v8_class_t v8_ExternalIntArray_class = {
	"ExternalIntArray", &v8_ExternalArray_class, v8_ExternalIntArray_fields
};

/* ExternalUnsignedIntArray class */
v8_field_t v8_ExternalUnsignedIntArray_fields[] = {
	{ NULL }
};

v8_class_t v8_ExternalUnsignedIntArray_class = {
	"ExternalUnsignedIntArray", &v8_ExternalArray_class, v8_ExternalUnsignedIntArray_fields
};

/* ExternalFloatArray class */
v8_field_t v8_ExternalFloatArray_fields[] = {
	{ NULL }
};

v8_class_t v8_ExternalFloatArray_class = {
	"ExternalFloatArray", &v8_ExternalArray_class, v8_ExternalFloatArray_fields
};

/* DeoptimizationInputData class */
v8_field_t v8_DeoptimizationInputData_fields[] = {
	{ NULL }
};

v8_class_t v8_DeoptimizationInputData_class = {
	"DeoptimizationInputData", &v8_FixedArray_class, v8_DeoptimizationInputData_fields
};

/* DeoptimizationOutputData class */
v8_field_t v8_DeoptimizationOutputData_fields[] = {
	{ NULL }
};

v8_class_t v8_DeoptimizationOutputData_class = {
	"DeoptimizationOutputData", &v8_FixedArray_class, v8_DeoptimizationOutputData_fields
};

/* Script class */
v8_field_t v8_Script_fields[] = {
	{ "source", V8_OFF_SCRIPT_SOURCE, sizeof (uintptr_t) },
	{ "name", V8_OFF_SCRIPT_NAME, sizeof (uintptr_t) },
	{ "line_offset", V8_OFF_SCRIPT_LINE_OFFSET, sizeof (uintptr_t) },
	{ "column_offset", V8_OFF_SCRIPT_COLUMN_OFFSET, sizeof (uintptr_t) },
	{ "data", V8_OFF_SCRIPT_DATA, sizeof (uintptr_t) },
	{ "context_data", V8_OFF_SCRIPT_CONTEXT_DATA, sizeof (uintptr_t) },
	{ "wrapper", V8_OFF_SCRIPT_WRAPPER, sizeof (uintptr_t) },
	{ "type", V8_OFF_SCRIPT_TYPE, sizeof (uintptr_t) },
	{ "compilation_type", V8_OFF_SCRIPT_COMPILATION_TYPE, sizeof (uintptr_t) },
	{ "line_ends", V8_OFF_SCRIPT_LINE_ENDS, sizeof (uintptr_t) },
	{ "id", V8_OFF_SCRIPT_ID, sizeof (uintptr_t) },
	{ "eval_from_shared", V8_OFF_SCRIPT_EVAL_FROM_SHARED, sizeof (uintptr_t) },
	{ "eval_from_instructions_offset", V8_OFF_SCRIPT_EVAL_FROM_INSTRUCTIONS_OFFSET, sizeof (uintptr_t) },
	{ NULL }
};

v8_class_t v8_Script_class = {
	"Script", &v8_Struct_class, v8_Script_fields
};

/* JSFunction class */
v8_field_t v8_JSFunction_fields[] = {
	{ "prototype_or_initial_map", V8_OFF_JSFUNCTION_PROTOTYPE_OR_INITIAL_MAP, sizeof (uintptr_t) },
	{ "shared", V8_OFF_JSFUNCTION_SHARED, sizeof (uintptr_t) },
	{ "literals", V8_OFF_JSFUNCTION_LITERALS, sizeof (uintptr_t) },
	{ "next_function_link", V8_OFF_JSFUNCTION_NEXT_FUNCTION_LINK, sizeof (uintptr_t) },
	{ NULL }
};

v8_class_t v8_JSFunction_class = {
	"JSFunction", &v8_JSObject_class, v8_JSFunction_fields
};

/* JSGlobalProxy class */
v8_field_t v8_JSGlobalProxy_fields[] = {
	{ "context", V8_OFF_JSGLOBALPROXY_CONTEXT, sizeof (uintptr_t) },
	{ NULL }
};

v8_class_t v8_JSGlobalProxy_class = {
	"JSGlobalProxy", &v8_JSObject_class, v8_JSGlobalProxy_fields
};

/* GlobalObject class */
v8_field_t v8_GlobalObject_fields[] = {
	{ "builtins", V8_OFF_GLOBALOBJECT_BUILTINS, sizeof (uintptr_t) },
	{ "global_context", V8_OFF_GLOBALOBJECT_GLOBAL_CONTEXT, sizeof (uintptr_t) },
	{ "global_receiver", V8_OFF_GLOBALOBJECT_GLOBAL_RECEIVER, sizeof (uintptr_t) },
	{ NULL }
};

v8_class_t v8_GlobalObject_class = {
	"GlobalObject", &v8_JSObject_class, v8_GlobalObject_fields
};

/* JSValue class */
v8_field_t v8_JSValue_fields[] = {
	{ "value", V8_OFF_JSVALUE_VALUE, sizeof (uintptr_t) },
	{ NULL }
};

v8_class_t v8_JSValue_class = {
	"JSValue", &v8_JSObject_class, v8_JSValue_fields
};

/* JSMessageObject class */
v8_field_t v8_JSMessageObject_fields[] = {
	{ "type", V8_OFF_JSMESSAGEOBJECT_TYPE, sizeof (uintptr_t) },
	{ "arguments", V8_OFF_JSMESSAGEOBJECT_ARGUMENTS, sizeof (uintptr_t) },
	{ "script", V8_OFF_JSMESSAGEOBJECT_SCRIPT, sizeof (uintptr_t) },
	{ "stack_trace", V8_OFF_JSMESSAGEOBJECT_STACK_TRACE, sizeof (uintptr_t) },
	{ "stack_frames", V8_OFF_JSMESSAGEOBJECT_STACK_FRAMES, sizeof (uintptr_t) },
	{ "start_position", V8_OFF_JSMESSAGEOBJECT_START_POSITION, sizeof (uintptr_t) },
	{ "end_position", V8_OFF_JSMESSAGEOBJECT_END_POSITION, sizeof (uintptr_t) },
	{ NULL }
};

v8_class_t v8_JSMessageObject_class = {
	"JSMessageObject", &v8_JSObject_class, v8_JSMessageObject_fields
};

/* JSRegExp class */
v8_field_t v8_JSRegExp_fields[] = {
	{ "data", V8_OFF_JSREGEXP_DATA, sizeof (uintptr_t) },
	{ NULL }
};

v8_class_t v8_JSRegExp_class = {
	"JSRegExp", &v8_JSObject_class, v8_JSRegExp_fields
};

/* CodeCache class */
v8_field_t v8_CodeCache_fields[] = {
	{ "default_cache", V8_OFF_CODECACHE_DEFAULT_CACHE, sizeof (uintptr_t) },
	{ "normal_type_cache", V8_OFF_CODECACHE_NORMAL_TYPE_CACHE, sizeof (uintptr_t) },
	{ NULL }
};

v8_class_t v8_CodeCache_class = {
	"CodeCache", &v8_Struct_class, v8_CodeCache_fields
};

/* SeqString class */
v8_field_t v8_SeqString_fields[] = {
	{ NULL }
};

v8_class_t v8_SeqString_class = {
	"SeqString", &v8_String_class, v8_SeqString_fields
};

/* ConsString class */
v8_field_t v8_ConsString_fields[] = {
	{ "first", V8_OFF_CONSSTRING_FIRST, sizeof (uintptr_t) },
	{ "second", V8_OFF_CONSSTRING_SECOND, sizeof (uintptr_t) },
	{ NULL }
};

v8_class_t v8_ConsString_class = {
	"ConsString", &v8_String_class, v8_ConsString_fields
};

/* ExternalString class */
v8_field_t v8_ExternalString_fields[] = {
	{ "resource", V8_OFF_EXTERNALSTRING_RESOURCE, sizeof (uintptr_t) },
	{ NULL }
};

v8_class_t v8_ExternalString_class = {
	"ExternalString", &v8_String_class, v8_ExternalString_fields
};

/* JSArray class */
v8_field_t v8_JSArray_fields[] = {
	{ "length", V8_OFF_JSARRAY_LENGTH, sizeof (uintptr_t) },
	{ NULL }
};

v8_class_t v8_JSArray_class = {
	"JSArray", &v8_JSObject_class, v8_JSArray_fields
};

/* AccessorInfo class */
v8_field_t v8_AccessorInfo_fields[] = {
	{ "getter", V8_OFF_ACCESSORINFO_GETTER, sizeof (uintptr_t) },
	{ "setter", V8_OFF_ACCESSORINFO_SETTER, sizeof (uintptr_t) },
	{ "data", V8_OFF_ACCESSORINFO_DATA, sizeof (uintptr_t) },
	{ "name", V8_OFF_ACCESSORINFO_NAME, sizeof (uintptr_t) },
	{ "flag", V8_OFF_ACCESSORINFO_FLAG, sizeof (uintptr_t) },
	{ NULL }
};

v8_class_t v8_AccessorInfo_class = {
	"AccessorInfo", &v8_Struct_class, v8_AccessorInfo_fields
};

/* AccessCheckInfo class */
v8_field_t v8_AccessCheckInfo_fields[] = {
	{ "named_callback", V8_OFF_ACCESSCHECKINFO_NAMED_CALLBACK, sizeof (uintptr_t) },
	{ "indexed_callback", V8_OFF_ACCESSCHECKINFO_INDEXED_CALLBACK, sizeof (uintptr_t) },
	{ "data", V8_OFF_ACCESSCHECKINFO_DATA, sizeof (uintptr_t) },
	{ NULL }
};

v8_class_t v8_AccessCheckInfo_class = {
	"AccessCheckInfo", &v8_Struct_class, v8_AccessCheckInfo_fields
};

/* InterceptorInfo class */
v8_field_t v8_InterceptorInfo_fields[] = {
	{ "getter", V8_OFF_INTERCEPTORINFO_GETTER, sizeof (uintptr_t) },
	{ "setter", V8_OFF_INTERCEPTORINFO_SETTER, sizeof (uintptr_t) },
	{ "query", V8_OFF_INTERCEPTORINFO_QUERY, sizeof (uintptr_t) },
	{ "deleter", V8_OFF_INTERCEPTORINFO_DELETER, sizeof (uintptr_t) },
	{ "enumerator", V8_OFF_INTERCEPTORINFO_ENUMERATOR, sizeof (uintptr_t) },
	{ "data", V8_OFF_INTERCEPTORINFO_DATA, sizeof (uintptr_t) },
	{ NULL }
};

v8_class_t v8_InterceptorInfo_class = {
	"InterceptorInfo", &v8_Struct_class, v8_InterceptorInfo_fields
};

/* CallHandlerInfo class */
v8_field_t v8_CallHandlerInfo_fields[] = {
	{ "callback", V8_OFF_CALLHANDLERINFO_CALLBACK, sizeof (uintptr_t) },
	{ "data", V8_OFF_CALLHANDLERINFO_DATA, sizeof (uintptr_t) },
	{ NULL }
};

v8_class_t v8_CallHandlerInfo_class = {
	"CallHandlerInfo", &v8_Struct_class, v8_CallHandlerInfo_fields
};

/* TemplateInfo class */
v8_field_t v8_TemplateInfo_fields[] = {
	{ "tag", V8_OFF_TEMPLATEINFO_TAG, sizeof (uintptr_t) },
	{ "property_list", V8_OFF_TEMPLATEINFO_PROPERTY_LIST, sizeof (uintptr_t) },
	{ NULL }
};

v8_class_t v8_TemplateInfo_class = {
	"TemplateInfo", &v8_Struct_class, v8_TemplateInfo_fields
};

/* SignatureInfo class */
v8_field_t v8_SignatureInfo_fields[] = {
	{ "receiver", V8_OFF_SIGNATUREINFO_RECEIVER, sizeof (uintptr_t) },
	{ "args", V8_OFF_SIGNATUREINFO_ARGS, sizeof (uintptr_t) },
	{ NULL }
};

v8_class_t v8_SignatureInfo_class = {
	"SignatureInfo", &v8_Struct_class, v8_SignatureInfo_fields
};

/* TypeSwitchInfo class */
v8_field_t v8_TypeSwitchInfo_fields[] = {
	{ "types", V8_OFF_TYPESWITCHINFO_TYPES, sizeof (uintptr_t) },
	{ NULL }
};

v8_class_t v8_TypeSwitchInfo_class = {
	"TypeSwitchInfo", &v8_Struct_class, v8_TypeSwitchInfo_fields
};

/* DebugInfo class */
v8_field_t v8_DebugInfo_fields[] = {
	{ "shared", V8_OFF_DEBUGINFO_SHARED, sizeof (uintptr_t) },
	{ "original_code", V8_OFF_DEBUGINFO_ORIGINAL_CODE, sizeof (uintptr_t) },
	{ "code", V8_OFF_DEBUGINFO_CODE, sizeof (uintptr_t) },
	{ "break_points", V8_OFF_DEBUGINFO_BREAK_POINTS, sizeof (uintptr_t) },
	{ NULL }
};

v8_class_t v8_DebugInfo_class = {
	"DebugInfo", &v8_Struct_class, v8_DebugInfo_fields
};

/* BreakPointInfo class */
v8_field_t v8_BreakPointInfo_fields[] = {
	{ "code_position", V8_OFF_BREAKPOINTINFO_CODE_POSITION, sizeof (uintptr_t) },
	{ "source_position", V8_OFF_BREAKPOINTINFO_SOURCE_POSITION, sizeof (uintptr_t) },
	{ "statement_position", V8_OFF_BREAKPOINTINFO_STATEMENT_POSITION, sizeof (uintptr_t) },
	{ "break_point_objects", V8_OFF_BREAKPOINTINFO_BREAK_POINT_OBJECTS, sizeof (uintptr_t) },
	{ NULL }
};

v8_class_t v8_BreakPointInfo_class = {
	"BreakPointInfo", &v8_Struct_class, v8_BreakPointInfo_fields
};

/* JSGlobalObject class */
v8_field_t v8_JSGlobalObject_fields[] = {
	{ NULL }
};

v8_class_t v8_JSGlobalObject_class = {
	"JSGlobalObject", &v8_GlobalObject_class, v8_JSGlobalObject_fields
};

/* JSBuiltinsObject class */
v8_field_t v8_JSBuiltinsObject_fields[] = {
	{ NULL }
};

v8_class_t v8_JSBuiltinsObject_class = {
	"JSBuiltinsObject", &v8_GlobalObject_class, v8_JSBuiltinsObject_fields
};

/* SeqAsciiString class */
v8_field_t v8_SeqAsciiString_fields[] = {
	{ "chars", V8_OFF_SEQASCIISTRING_CHARS, sizeof (uintptr_t) },
	{ NULL }
};

v8_class_t v8_SeqAsciiString_class = {
	"SeqAsciiString", &v8_SeqString_class, v8_SeqAsciiString_fields
};

/* SeqTwoByteString class */
v8_field_t v8_SeqTwoByteString_fields[] = {
	{ NULL }
};

v8_class_t v8_SeqTwoByteString_class = {
	"SeqTwoByteString", &v8_SeqString_class, v8_SeqTwoByteString_fields
};

/* ExternalAsciiString class */
v8_field_t v8_ExternalAsciiString_fields[] = {
	{ NULL }
};

v8_class_t v8_ExternalAsciiString_class = {
	"ExternalAsciiString", &v8_ExternalString_class, v8_ExternalAsciiString_fields
};

/* ExternalTwoByteString class */
v8_field_t v8_ExternalTwoByteString_fields[] = {
	{ NULL }
};

v8_class_t v8_ExternalTwoByteString_class = {
	"ExternalTwoByteString", &v8_ExternalString_class, v8_ExternalTwoByteString_fields
};

/* JSRegExpResult class */
v8_field_t v8_JSRegExpResult_fields[] = {
	{ NULL }
};

v8_class_t v8_JSRegExpResult_class = {
	"JSRegExpResult", &v8_JSArray_class, v8_JSRegExpResult_fields
};

/* FunctionTemplateInfo class */
v8_field_t v8_FunctionTemplateInfo_fields[] = {
	{ "serial_number", V8_OFF_FUNCTIONTEMPLATEINFO_SERIAL_NUMBER, sizeof (uintptr_t) },
	{ "call_code", V8_OFF_FUNCTIONTEMPLATEINFO_CALL_CODE, sizeof (uintptr_t) },
	{ "property_accessors", V8_OFF_FUNCTIONTEMPLATEINFO_PROPERTY_ACCESSORS, sizeof (uintptr_t) },
	{ "prototype_template", V8_OFF_FUNCTIONTEMPLATEINFO_PROTOTYPE_TEMPLATE, sizeof (uintptr_t) },
	{ "parent_template", V8_OFF_FUNCTIONTEMPLATEINFO_PARENT_TEMPLATE, sizeof (uintptr_t) },
	{ "named_property_handler", V8_OFF_FUNCTIONTEMPLATEINFO_NAMED_PROPERTY_HANDLER, sizeof (uintptr_t) },
	{ "indexed_property_handler", V8_OFF_FUNCTIONTEMPLATEINFO_INDEXED_PROPERTY_HANDLER, sizeof (uintptr_t) },
	{ "instance_template", V8_OFF_FUNCTIONTEMPLATEINFO_INSTANCE_TEMPLATE, sizeof (uintptr_t) },
	{ "class_name", V8_OFF_FUNCTIONTEMPLATEINFO_CLASS_NAME, sizeof (uintptr_t) },
	{ "signature", V8_OFF_FUNCTIONTEMPLATEINFO_SIGNATURE, sizeof (uintptr_t) },
	{ "instance_call_handler", V8_OFF_FUNCTIONTEMPLATEINFO_INSTANCE_CALL_HANDLER, sizeof (uintptr_t) },
	{ "access_check_info", V8_OFF_FUNCTIONTEMPLATEINFO_ACCESS_CHECK_INFO, sizeof (uintptr_t) },
	{ "flag", V8_OFF_FUNCTIONTEMPLATEINFO_FLAG, sizeof (uintptr_t) },
	{ NULL }
};

v8_class_t v8_FunctionTemplateInfo_class = {
	"FunctionTemplateInfo", &v8_TemplateInfo_class, v8_FunctionTemplateInfo_fields
};

/* ObjectTemplateInfo class */
v8_field_t v8_ObjectTemplateInfo_fields[] = {
	{ "constructor", V8_OFF_OBJECTTEMPLATEINFO_CONSTRUCTOR, sizeof (uintptr_t) },
	{ "internal_field_count", V8_OFF_OBJECTTEMPLATEINFO_INTERNAL_FIELD_COUNT, sizeof (uintptr_t) },
	{ NULL }
};

v8_class_t v8_ObjectTemplateInfo_class = {
	"ObjectTemplateInfo", &v8_TemplateInfo_class, v8_ObjectTemplateInfo_fields
};


v8_class_t *v8_classes[] = {
	&v8_MaybeObject_class,
	&v8_Relocatable_class,
	&v8_AllStatic_class,
	&v8_Object_class,
	&v8_Failure_class,
	&v8_FlatStringReader_class,
	&v8_BooleanBit_class,
	&v8_Smi_class,
	&v8_HeapObject_class,
	&v8_HeapNumber_class,
	&v8_JSObject_class,
	&v8_FixedArray_class,
	&v8_ByteArray_class,
	&v8_PixelArray_class,
	&v8_ExternalArray_class,
	&v8_Code_class,
	&v8_Map_class,
	&v8_Struct_class,
	&v8_SharedFunctionInfo_class,
	&v8_String_class,
	&v8_Oddball_class,
	&v8_JSGlobalPropertyCell_class,
	&v8_Proxy_class,
	&v8_DescriptorArray_class,
	&v8_HashTable_class,
	&v8_JSFunctionResultCache_class,
	&v8_NormalizedMapCache_class,
	&v8_ExternalByteArray_class,
	&v8_ExternalUnsignedByteArray_class,
	&v8_ExternalShortArray_class,
	&v8_ExternalUnsignedShortArray_class,
	&v8_ExternalIntArray_class,
	&v8_ExternalUnsignedIntArray_class,
	&v8_ExternalFloatArray_class,
	&v8_DeoptimizationInputData_class,
	&v8_DeoptimizationOutputData_class,
	&v8_Script_class,
	&v8_JSFunction_class,
	&v8_JSGlobalProxy_class,
	&v8_GlobalObject_class,
	&v8_JSValue_class,
	&v8_JSMessageObject_class,
	&v8_JSRegExp_class,
	&v8_CodeCache_class,
	&v8_SeqString_class,
	&v8_ConsString_class,
	&v8_ExternalString_class,
	&v8_JSArray_class,
	&v8_AccessorInfo_class,
	&v8_AccessCheckInfo_class,
	&v8_InterceptorInfo_class,
	&v8_CallHandlerInfo_class,
	&v8_TemplateInfo_class,
	&v8_SignatureInfo_class,
	&v8_TypeSwitchInfo_class,
	&v8_DebugInfo_class,
	&v8_BreakPointInfo_class,
	&v8_JSGlobalObject_class,
	&v8_JSBuiltinsObject_class,
	&v8_SeqAsciiString_class,
	&v8_SeqTwoByteString_class,
	&v8_ExternalAsciiString_class,
	&v8_ExternalTwoByteString_class,
	&v8_JSRegExpResult_class,
	&v8_FunctionTemplateInfo_class,
	&v8_ObjectTemplateInfo_class,
	NULL
};

