/*
 * mdb(1M) module for debugging the V8 JavaScript engine.  This implementation
 * assumes 32-bit x86.
 */

#include <assert.h>
#include <string.h>

#include <sys/mdb_modapi.h>

/*
 * Hardcoded classes, fields, and types for V8 heap objects.  These should
 * eventually be generated by the V8 build process.
 */

#define	V8_TYPE_NOTSTRING		0x80	/* FIRST_NONSTRING_TYPE */

#define	V8_MASK_SMI_TAG			0x1	/* kSmiTagMask */

#define	V8_MASK_HEAPOBJECT_TAG		0x3	/* kHeapObjectTagMask */
#define	V8_TAG_HEAPOBJECT		0x1	/* kHeapObjectTag */
#define	V8_TAG_FAILURE			0x3	/* kFailureTag */

#define	V8_MASK_STRENC			0x4	/* kStringEncodingMask */
#define	V8_TAG_STRENC_ASCII		0x4	/* kAsciiStringTag */

#define	V8_MASK_STRREP			0x3	/* kStringRepresentationMask */
#define	V8_TAG_STRREP_SEQ		0x0	/* kSeqStringTag */
#define	V8_TAG_STRREP_CONS		0x1	/* kConsStringTag */
#define	V8_TAG_STRREP_EXT		0x2	/* kExternalStringTag */

/*
 * The following constants represents field offsets for instances of a
 * particular C++ class.  They're named V8_OFF_(CLASSNAME)_(FIELDNAME).  The
 * offsets are defined relative to the start of the corresponding object in
 * memory.  However, while V8 heap objects are always 4-byte aligned, heap
 * object pointers always have the last bit set.  Rather than modify the
 * pointers everywhere we use them, we adjust the offset definitions here (as V8
 * does internally -- see the READ_FIELD() and FIELD_ADDR() macros in
 * v8/src/objects-inl.h.)
 */
#define	V8_OFF_HEAP(x)			((x) - V8_TAG_HEAPOBJECT)

/* See JavaScriptFrameConstants::kFunctionOffset. */
#define	V8_OFF_FP_FUNCTION		(-0x8)

#define	V8_OFF_FUNC_FUNCINFO		V8_OFF_HEAP(0x14)

#define	V8_OFF_FUNCINFO_NAME		V8_OFF_HEAP(0x4)
#define	V8_OFF_FUNCINFO_SCRIPT		V8_OFF_HEAP(0x1c)
#define	V8_OFF_FUNCINFO_FUNCTOKPOS	V8_OFF_HEAP(0x4c)

#define	V8_OFF_SCRIPT_NAME		V8_OFF_HEAP(0x8)
#define	V8_OFF_SCRIPT_LINEENDS		V8_OFF_HEAP(0x28)

#define	V8_OFF_MAP_INSTANCEATTRS	V8_OFF_HEAP(0x8)

#define	V8_OFF_FIXEDARRAY_SIZE		V8_OFF_HEAP(0x4)
#define	V8_OFF_FIXEDARRAY_DATA		V8_OFF_HEAP(0x8)

#define	V8_OFF_STRING_LENGTH		V8_OFF_HEAP(0x4)
#define	V8_OFF_SEQSTRING_CHARS		V8_OFF_HEAP(0xc)
#define	V8_OFF_CONSSTRING_CAR		V8_OFF_HEAP(0xc)
#define	V8_OFF_CONSSTRING_CDR		V8_OFF_HEAP(0x10)

typedef struct v8_class {
	const char *v8c_name;		/* heap object class name */
	struct v8_class *v8c_parent;	/* parent class (inheritance) */
	struct v8_field *v8c_fields;	/* array of class fields */
	size_t v8c_start;		/* filled in dynamically */
	size_t v8c_end;			/* filled in dynamically */
} v8_class_t;

typedef struct v8_field {
	const char 	*v8f_name;	/* field name */
	const size_t	v8f_size;	/* field size */
} v8_field_t;

v8_field_t v8_HeapObject_fields[] = {
	{ "Map",			sizeof (uintptr_t) },
	{ NULL }
};

v8_class_t v8_HeapObject_class = {
	"HeapObject", NULL, v8_HeapObject_fields
};

v8_field_t v8_JSObject_fields[] = {
	{ "Properties", 		sizeof (uintptr_t) },
	{ "Elements", 			sizeof (uintptr_t) },
	{ NULL }
};

v8_class_t v8_JSObject_class = {
	"JSObject", &v8_HeapObject_class, v8_JSObject_fields
};

v8_field_t v8_JSFunction_fields[] = {
	{ "CodeEntry", 			sizeof (uintptr_t) },
	{ "PrototypeOrInitialMap", 	sizeof (uintptr_t) },
	{ "SharedFunctionInfo", 	sizeof (uintptr_t) },
	{ "Context", 			sizeof (uintptr_t) },
	{ "Literals", 			sizeof (uintptr_t) },
	{ "NonWeakFieldsEnd", 		sizeof (uintptr_t) },
	{ "NextFunctionLinkOffset", 	sizeof (uintptr_t) },
	{ NULL }
};

v8_class_t v8_JSFunction_class = {
	"JSFunction", &v8_JSObject_class, v8_JSFunction_fields
};

/*
 * Lists all V8 heap object classes that we know how to print.  Each class's
 * parent must be defined before the class itself.
 */
v8_class_t *v8_classes[] = {
	&v8_HeapObject_class,
	&v8_JSObject_class,
	&v8_JSFunction_class,
};

static const int v8_nclasses = sizeof (v8_classes) / sizeof (v8_classes[0]);

/*
 * Describes the V8 "InstanceType" enum values that do NOT represent string
 * types.  String types (having value less than 0x80) are determined
 * programmatically.
 */
typedef struct {
	const char 	*v8t_name;	/* type name */
	uint_t		v8t_type;	/* actual type value */
} v8_instance_type_t;

static v8_instance_type_t v8_types[] = {
	{ "Map", 			V8_TYPE_NOTSTRING	},
	{ "Code" 						},
	{ "Oddball" 						},
	{ "JSGlobalPropertyCell"				},
	{ "HeapNumber"						},
	{ "Proxy"						},
	{ "ByteArray" 						},
	{ "PixelArray"						},
	{ "ExternalByteArray"					},
	{ "ExternalUnsignedByteArray"				},
	{ "ExternalShortArray"					},
	{ "ExternalUnsignedShortArray"				},
	{ "ExternalIntArray"					},
	{ "ExternalUnsignedIntArray"				},
	{ "ExternalFloatArray"					},
	{ "Filler"						},
	{ "AccessorInfo"					},
	{ "AccessCheckInfo"					},
	{ "InterceptorInfo"					},
	{ "CallHandlerInfo"					},
	{ "FunctionTemplateInfo"				},
	{ "ObjectTemplateInfo"					},
	{ "SignatureInfo"					},
	{ "TypeSwitchInfo"					},
	{ "Script"						},
	{ "CodeCache"						},
	{ "DebugInfo"						},
	{ "BreakPointInfo"					},
	{ "FixedArray"						},
	{ "SharedFunctionInfo"					},
	{ "JSMessageObject"					},
	{ "JSValue"						},
	{ "JSObject"						},
	{ "JSContextExtensionObject"				},
	{ "JSGlobalObject"					},
	{ "JSBuiltinsObject"					},
	{ "JSGlobalProxy"					},
	{ "JSArray"						},
	{ "JSRegexp"						},
	{ "JSFunction"						},
	{ NULL }
};

/*
 * For convenience, we allow the offset to be omitted for fields specified
 * above.  We fill in the true offset here as well as the "end" field.
 */
static void
init_classes(void)
{
	v8_class_t *clp;
	v8_field_t *flp;
	int ii;

	for (ii = 0; ii < v8_nclasses; ii++) {
		clp = v8_classes[ii];

		assert(clp->v8c_start == 0);
		assert(clp->v8c_end == 0);

		if (clp->v8c_parent != NULL) {
			/* parent must be defined first. */
			assert(clp->v8c_parent->v8c_end > 0);
			clp->v8c_start = clp->v8c_parent->v8c_end;
		}

		clp->v8c_end = clp->v8c_start;
		for (flp = &clp->v8c_fields[0]; flp->v8f_name != NULL; flp++)
			clp->v8c_end += flp->v8f_size;
	}
}

/*
 * For convenience, we allow values to be omitted from the structures describing
 * the InstanceType enum above.  We fill in the true values here using the same
 * rules as for standard C enum definitions.
 */
static void
init_types(void)
{
	v8_instance_type_t *itp;
	uint8_t val = 0;

	for (itp = v8_types; itp->v8t_name != NULL; itp++) {
		if (itp->v8t_type == 0)
			itp->v8t_type = val;

		val = itp->v8t_type + 1;
	}
}

/*
 * Utility functions
 */

static int
read_heap_ptr(uintptr_t *valp, uintptr_t addr, uintptr_t off)
{
	if (mdb_vread(valp, sizeof (*valp), addr + off) == sizeof (*valp))
		return (0);

	mdb_warn("failed to read heap value at %p", addr + off);
	return (-1);
}

static int
read_heap_smi(uintptr_t *valp, uintptr_t addr, uintptr_t off)
{
	if (mdb_vread(valp, sizeof (*valp), addr + off) != sizeof (*valp)) {
		mdb_warn("failed to read heap value at %p", addr + off);
		return (-1);
	}

	/*
	 * Recall that V8 stores small integers on the heap using the upper 31
	 * bits, so we must shift the word over to get the true value.  The
	 * low-order bit must be clear if this is really an SMI.
	 */
	if ((*valp & V8_MASK_SMI_TAG) != 0) {
		mdb_warn("expected SMI, got %p", *valp);
		return (-1);
	}

	*valp >>= 1;
	return (0);
}

/*
 * Given a heap object, returns in *valp the byte describing the type of the
 * object.  This is shorthand for first retrieving the Map at the start of the
 * heap object and then retrieving the type byte from the Map object.
 */
static int
read_typebyte(uint8_t *valp, uintptr_t addr)
{
	uintptr_t mapaddr;

	if (read_heap_ptr(&mapaddr, addr, -1) != DCMD_OK)
		return (-1);

	if ((mapaddr & V8_MASK_HEAPOBJECT_TAG) != V8_TAG_HEAPOBJECT) {
		mdb_warn("heap object map is not itself a heap object\n");
		return (-1);
	}

	if (mdb_vread(valp, sizeof (*valp),
	    mapaddr + V8_OFF_MAP_INSTANCEATTRS) != sizeof (*valp)) {
		mdb_warn("failed to read type byte");
		return (-1);
	}

	return (0);
}

/*
 * Invoke "func" for each parent class of "clp", including "clp" itself.
 */
static int
obj_iter_classes(uintptr_t addr, v8_class_t *clp,
    int (*func)(uintptr_t, v8_class_t *))
{
	int rv;

	if (clp->v8c_parent != NULL &&
	    (rv = obj_iter_classes(addr, clp->v8c_parent, func)) != 0)
		return (rv);

	return (func(addr, clp));
}

/*
 * Print out the fields of the given object that come from the given class.
 */
static int
obj_print_fields(uintptr_t baddr, v8_class_t *clp)
{
	v8_field_t *flp;
	uintptr_t addr, value;
	int rv;

	addr = baddr + clp->v8c_start;

	for (flp = clp->v8c_fields; flp->v8f_name != NULL; flp++) {
		assert(flp->v8f_size == sizeof (uintptr_t));
		rv = mdb_vread((void *)&value, sizeof (value), addr);

		if (rv == sizeof (value))
			mdb_printf("%8p  %-20s  %-25s  %8p  %8p\n", addr,
			    clp->v8c_name, flp->v8f_name, value, value >> 1);
		else
			mdb_printf("%8p  %-20s  %-25s  %s\n", addr,
			    clp->v8c_name, flp->v8f_name, "<unreadable>");

		addr += flp->v8f_size;
	}

	return (DCMD_OK);
}

/*
 * Print out all fields of the given object, starting with the root of the class
 * hierarchy and working down the most specific type.
 */
static int
obj_print_class(uintptr_t addr, v8_class_t *clp)
{
	int rv;

	(void) mdb_inc_indent(4);
	mdb_printf("%8s  %-20s  %-25s  %-8s  %-8s\n",
	    "ADDR", "CLASS", "FIELD", "PTRVAL", "SMIVAL");
	rv = obj_iter_classes(addr - V8_TAG_HEAPOBJECT, clp, obj_print_fields);
	(void) mdb_dec_indent(4);

	return (rv);
}

/*
 * Returns in "buf" a description of the type of "addr".
 */
static int
obj_jstype(uintptr_t addr, char *buf, size_t len)
{
	uint8_t typebyte;
	v8_instance_type_t *itp;

	buf[0] = '\0';

	if ((addr & V8_MASK_HEAPOBJECT_TAG) == V8_TAG_FAILURE) {
		(void) mdb_snprintf(buf, len, "'Failure' object");
		return (0);
	}

	if ((addr & V8_MASK_SMI_TAG) == 0) {
		(void) mdb_snprintf(buf, len, "SMI: value = 0x%x = %d",
		    addr >> 1, addr >> 1);
		return (0);
	}

	if (read_typebyte(&typebyte, addr) != 0)
		return (-1);

	if ((typebyte & V8_TYPE_NOTSTRING) != 0) {
		for (itp = v8_types; itp->v8t_name != NULL; itp++) {
			if (itp->v8t_type == typebyte) {
				(void) strlcpy(buf, itp->v8t_name, len);
				return (DCMD_OK);
			}
		}

		(void) mdb_snprintf(buf, len, "unknown type 0x%x",
		    itp->v8t_type);
		return (0);
	}

	(void) strlcpy(buf, (typebyte & V8_MASK_STRENC) == V8_TAG_STRENC_ASCII ?
	    "ascii " : "two-byte ", len);

	switch (typebyte & V8_MASK_STRREP) {
	case V8_TAG_STRREP_SEQ:
		(void) strlcat(buf, "SeqString", len);
		break;
	case V8_TAG_STRREP_CONS:
		(void) strlcat(buf, "ConsString", len);
		break;
	case V8_TAG_STRREP_EXT:
		(void) strlcat(buf, "ExternalString", len);
		break;
	}

	return (0);
}

/*
 * Print the ASCII string for the given field value.
 */
static int
print_strval(uintptr_t addr, boolean_t verbose)
{
	uint8_t typebyte;
	uintptr_t len, rlen, ptr1, ptr2;
	int err = 0;
	char buf[256];

	if (read_typebyte(&typebyte, addr) != 0)
		return (0);

	if ((typebyte & V8_TYPE_NOTSTRING) != 0) {
		mdb_printf("<invalid string>");
		return (0);
	}

	if ((typebyte & V8_MASK_STRENC) != V8_TAG_STRENC_ASCII) {
		mdb_printf("<two-byte string>");
		return (0);
	}

	if (verbose) {
		(void) obj_jstype(addr, buf, sizeof (buf));
		mdb_printf("%s\n", buf);
		(void) mdb_inc_indent(4);
	}

	switch (typebyte & V8_MASK_STRREP) {
	case V8_TAG_STRREP_SEQ:
		err |= read_heap_smi(&len, addr, V8_OFF_STRING_LENGTH);

		if (err != 0)
			break;

		rlen = len <= sizeof (buf) - 1 ? len :
		    sizeof (buf) - sizeof ("[...]");

		if (verbose) {
			mdb_printf("length: %d\n", len);
			mdb_printf("will read: %d\n", rlen);
		}

		if (rlen > 0 && mdb_vread(&buf, rlen,
		    addr + V8_OFF_SEQSTRING_CHARS) != rlen) {
			mdb_warn("failed to read SeqString data");
			err = -1;
			break;
		}

		buf[rlen] = '\0';

		if (rlen != len)
			(void) strlcat(buf, "[...]", sizeof (buf));

		if (verbose)
			mdb_printf("value: \"");

		mdb_printf("%s", buf);

		if (verbose)
			mdb_printf("\"\n");

		break;

	case V8_TAG_STRREP_CONS:
		err |= read_heap_ptr(&ptr1, addr, V8_OFF_CONSSTRING_CAR);
		err |= read_heap_ptr(&ptr2, addr, V8_OFF_CONSSTRING_CDR);

		if (err == 0) {
			if (verbose) {
				mdb_printf("ptr1: %p\n", ptr1);
				mdb_printf("ptr2: %p\n", ptr2);
			}

			err |= print_strval(ptr1, verbose);
		}

		if (err == 0)
			err |= print_strval(ptr2, verbose);

		break;

	case V8_TAG_STRREP_EXT:
		mdb_printf("<ExternalString>");
		break;
	}

	if (verbose)
		(void) mdb_dec_indent(4);

	return (err);
}

/*
 * Fill in "buf" with the line number of the given token position using the line
 * endings table in "lendsp".
 */
static int
func_line(uintptr_t lendsp, uintptr_t tokpos, char *buf, size_t buflen)
{
	uintptr_t size, bufsz, lower, upper, ii;
	uintptr_t *data;

	if (read_heap_smi(&size, lendsp, V8_OFF_FIXEDARRAY_SIZE) != 0)
		return (-1);

	bufsz = size * sizeof (data[0]);

	if ((data = mdb_alloc(bufsz, UM_NOSLEEP)) == NULL) {
		mdb_warn("failed to alloc %d bytes for FixedArray data", bufsz);
		return (-1);
	}

	if (mdb_vread(data, bufsz, lendsp + V8_OFF_FIXEDARRAY_DATA) != bufsz) {
		mdb_warn("failed to read FixedArray data");
		mdb_free(data, bufsz);
		return (-1);
	}

	lower = 0;
	upper = size - 1;

	if (tokpos > data[upper]) {
		(void) strlcpy(buf, "position out of range", buflen);
		mdb_free(data, bufsz);
		return (0);
	}

	if (tokpos <= data[0]) {
		(void) strlcpy(buf, "line 1", buflen);
		mdb_free(data, bufsz);
		return (0);
	}

	while (upper >= 1) {
		ii = (lower + upper) >> 1;
		if (tokpos > data[ii])
			lower = ii + 1;
		else if (tokpos <= data[ii - 1])
			upper = ii - 1;
		else
			break;
	}

	(void) mdb_snprintf(buf, buflen, "line %d", ii + 1);
	mdb_free(data, bufsz);
	return (0);
}

/*
 * dcmd implementations
 */

/* ARGSUSED */
int
dcmd_jsprint(uintptr_t addr, uint_t flags, int argc, const mdb_arg_t *argv)
{
	const char *rqclass;
	v8_class_t *clp;
	int ii;

	if (argc < 1 || argv[0].a_type != MDB_TYPE_STRING)
		return (DCMD_USAGE);

	rqclass = argv[0].a_un.a_str;
	for (ii = 0; ii < v8_nclasses; ii++) {
		clp = v8_classes[ii];
		if (strcmp(rqclass, clp->v8c_name) == 0)
			break;
	}

	if (ii == v8_nclasses) {
		mdb_printf("error: don't know about class '%s'\n", rqclass);
		mdb_printf("available classes:\n");
		(void) mdb_inc_indent(4);
		for (ii = 0; ii < v8_nclasses; ii++) {
			clp = v8_classes[ii];
			mdb_printf("%s\n", clp->v8c_name);
		}
		(void) mdb_dec_indent(4);
		return (DCMD_USAGE);
	}

	return (obj_print_class(addr, clp));
}

/* ARGSUSED */
static int
dcmd_jstypes(uintptr_t addr, uint_t flags, int argc, const mdb_arg_t *argv)
{
	v8_instance_type_t *itp;

	for (itp = v8_types; itp->v8t_name != NULL; itp++)
		mdb_printf("%-30s = 0x%02x\n", itp->v8t_name, itp->v8t_type);

	return (DCMD_OK);
}

/* ARGSUSED */
static int
dcmd_jstype(uintptr_t addr, uint_t flags, int argc, const mdb_arg_t *argv)
{
	char buf[64];

	if (obj_jstype(addr, buf, sizeof (buf)) != 0)
		return (DCMD_ERR);

	mdb_printf("0x%p: %s\n", addr, buf);
	return (DCMD_OK);
}

/* ARGSUSED */
static int
dcmd_jsframe(uintptr_t addr, uint_t flags, int argc, const mdb_arg_t *argv)
{
	uintptr_t funcp, funcinfop, tokpos, scriptp, lendsp, ptrp;
	boolean_t opt_v = B_FALSE;
	char typebuf[64];

	if (mdb_getopts(argc, argv, 'v', MDB_OPT_SETBITS, B_TRUE, &opt_v,
	    NULL) != argc)
		return (DCMD_USAGE);

	if (opt_v)
		mdb_printf("frame pointer: ");
	mdb_printf("%p", addr);
	if (opt_v)
		mdb_printf("\n");

	if (read_heap_ptr(&funcp, addr, V8_OFF_FP_FUNCTION) != 0)
		return (DCMD_ERR);

	if (opt_v) {
		(void) mdb_inc_indent(4);
		(void) obj_jstype(funcp, typebuf, sizeof (typebuf));
		mdb_printf("function: %p (%s)\n", funcp, typebuf);
	}

	if (read_heap_ptr(&funcinfop, funcp, V8_OFF_FUNC_FUNCINFO) != 0)
		return (DCMD_ERR);

	if (opt_v) {
		(void) mdb_inc_indent(4);
		(void) obj_jstype(funcinfop, typebuf, sizeof (typebuf));
		mdb_printf("shared function info: %p (%s)\n", funcinfop,
		    typebuf);
	}

	if (read_heap_ptr(&ptrp, funcinfop, V8_OFF_FUNCINFO_NAME) != 0)
		return (DCMD_ERR);

	if (opt_v) {
		(void) mdb_inc_indent(4);
		(void) obj_jstype(ptrp, typebuf, sizeof (typebuf));
		mdb_printf("function name: %p (%s: \"", ptrp, typebuf);
		(void) print_strval(ptrp, B_FALSE);
		mdb_printf("\")\n");
	} else {
		mdb_printf(" function \"");
		(void) print_strval(ptrp, B_FALSE);
		mdb_printf("\"");
	}

	/*
	 * Although the token position is technically an SMI, we're going to
	 * byte-compare it to other SMI values so we don't want decode it here.
	 */
	if (read_heap_ptr(&tokpos, funcinfop, V8_OFF_FUNCINFO_FUNCTOKPOS) != 0)
		return (DCMD_ERR);

	if (opt_v) {
		(void) obj_jstype(tokpos, typebuf, sizeof (typebuf));
		mdb_printf("function token position: %s\n", typebuf);
	}

	if (read_heap_ptr(&scriptp, funcinfop, V8_OFF_FUNCINFO_SCRIPT) != 0)
		return (DCMD_ERR);

	if (opt_v) {
		(void) obj_jstype(scriptp, typebuf, sizeof (typebuf));
		mdb_printf("script: %p (%s)\n", scriptp, typebuf);
	}

	if (read_heap_ptr(&ptrp, scriptp, V8_OFF_SCRIPT_NAME) != 0)
		return (DCMD_ERR);

	if (opt_v) {
		(void) mdb_inc_indent(4);
		(void) obj_jstype(ptrp, typebuf, sizeof (typebuf));
		mdb_printf("script name: %p (%s: \"", ptrp, typebuf);
		(void) print_strval(ptrp, B_FALSE);
		mdb_printf("\")\n");
	} else {
		mdb_printf(" defined at ");
		(void) print_strval(ptrp, B_FALSE);
		mdb_printf(" ");
	}

	if (read_heap_ptr(&lendsp, scriptp, V8_OFF_SCRIPT_LINEENDS) != 0)
		return (DCMD_ERR);

	/* XXX compare to "undefined" */
	if (opt_v) {
		(void) obj_jstype(lendsp, typebuf, sizeof (typebuf));
		mdb_printf("line endings: %p (%s)\n", lendsp, typebuf);

		(void) mdb_dec_indent(4);
		mdb_printf("function token at: ");
	}

	(void) func_line(lendsp, tokpos, typebuf, sizeof (typebuf));
	mdb_printf("%s\n", typebuf);

	if (opt_v) {
		(void) mdb_dec_indent(4);
		(void) mdb_dec_indent(4);
		(void) mdb_dec_indent(4);
	}

	return (DCMD_OK);
}

/* ARGSUSED */
static int
dcmd_jsstack(uintptr_t addr, uint_t flags, int argc, const mdb_arg_t *argv)
{
	mdb_tid_t tid = 1; /* assume JS thread is always tid 1 */
	mdb_reg_t reg;
	uintptr_t ebp, retp;
	int left = 20;

	mdb_printf("thread %d\n", tid);
	(void) mdb_inc_indent(4);

	if (mdb_getareg(tid, "ebp", &reg) != 0) {
		mdb_warn("failed to read ebp for thread %d", tid);
		return (DCMD_ERR);
	}

	ebp = (uintptr_t)reg;

	while (ebp != NULL && left-- > 0) {
		(void) mdb_call_dcmd("jsframe", ebp, DCMD_ADDRSPEC, 0, NULL);

		if (mdb_vread(&retp, sizeof (retp), ebp + sizeof (ebp)) !=
		    sizeof (retp) || retp == 0 ||
		    mdb_vread(&ebp, sizeof (ebp), ebp) != sizeof (ebp))
			break;
	}

	(void) mdb_dec_indent(4);

	return (DCMD_OK);
}

/* ARGSUSED */
static int
dcmd_jsstr(uintptr_t addr, uint_t flags, int argc, const mdb_arg_t *argv)
{
	boolean_t opt_v = B_FALSE;

	if (mdb_getopts(argc, argv, 'v', MDB_OPT_SETBITS, B_TRUE, &opt_v,
	    NULL) != argc)
		return (DCMD_USAGE);

	return (print_strval(addr, opt_v) == 0 ? DCMD_OK : DCMD_ERR);
}

/*
 * MDB linkage
 */

const mdb_dcmd_t v8_mdb_dcmds[] = {
	{ "jsframe", ":",	"print a V8 stack frame", dcmd_jsframe },
	{ "jsprint", ": class",	"print a V8 heap object", dcmd_jsprint },
	{ "jsstack", ":[-v]",	"print a V8 stacktrace", dcmd_jsstack },
	{ "jsstr", ":[-v]",	"print a V8 string", dcmd_jsstr },
	{ "jstype", ":", "print the type of a V8 heap object", dcmd_jstype },
	{ "jstypes", "", "print all V8 heap object types", dcmd_jstypes },
	{ NULL }
};

const mdb_walker_t v8_mdb_walkers[] = {
	{ NULL }
};

mdb_modinfo_t v8_mdb = {
	.mi_dvers = MDB_API_VERSION,
	.mi_dcmds = v8_mdb_dcmds,
	.mi_walkers = v8_mdb_walkers
};

const mdb_modinfo_t *
_mdb_init(void)
{
	init_classes();
	init_types();
	return (&v8_mdb);
}
