#!/bin/bash

#
# smf(5) start method for node-based CA services
#
. /lib/svc/share/smf_include.sh

function fail
{
	echo "$ns_arg0: $@"
	exit $SMF_EXIT_ERR_FATAL
}

function getprop
{
	local prop=$1
	svcprop -p com.joyent.ca,$prop $SMF_FMRI
}

function load_amqp
{
	local host

	if [[ -x $ns_amqpconfig ]]; then
		($ns_amqpconfig | while IFS="=" read key value; do
        		case $key in 
        		amqp_host)      echo "export AMQP_HOST=$value" ;;
        		amqp_port)      echo "export AMQP_PORT=$value" ;;
        		*)              echo "ignoring amqp-config key $key" >&2
        		esac
		done) > $ns_tmpfile || return 1
		. $ns_tmpfile && rm -f $ns_tmpfile || return 1
		return 0
	fi

	host=$(getprop caconfig/amqp-host)
	[[ -n $host ]] || \
	    fail "fatal: no amqp-config and no amqp-host property."
	export AMQP_HOST=$host
}

function load_mapi
{
	local host port user pass

	host=$(getprop caconfig/mapi-host)
	port=$(getprop caconfig/mapi-port)
	user=$(getprop caconfig/mapi-user)
	pass=$(getprop caconfig/mapi-password)

	export MAPI_HOST=$host
	export MAPI_PORT=$port
	export MAPI_USER=$user
	export MAPI_PASSWORD=$pass
}

function load_nodepath
{
	NODE_PATH=

	for subdir in node_modules lib/* deps/*; do
		[[ -d $subdir ]] || continue
		NODE_PATH="$NODE_PATH:$ns_root/$subdir"
	done

	export NODE_PATH
}

function load_geoip
{
	export GEOIP_DATABASE=/opt/local/share/GeoIP/GeoIPCity.dat
}

#
# svcprop can be relied upon to do great things. When you request a property
# that is the empty string, svcprop actually returns it as the string "". This
# means, that you cannot use [[ -z $foo ]] to properly check for an empty
# string. In fact, because of this, you have to explicitly use '""', otherwise
# bash interprets this as the empty string.
#
function load_dtracepath
{
	DTRACE_LIBPATH=$(getprop caconfig/dtrace-libpath)
	[[ $DTRACE_LIBPATH != '""' ]] && export DTRACE_LIBPATH
	echo "DTRACE_LIBPATH=$DTRACE_LIBPATH"
}

function run_realtime
{
	local pid=$1

	priocntl -s -c RT -i pid $pid
	[[ $? != 0 ]] && echo "Failed to move process into the RT class"
}

ns_arg0=$(basename $0)
ns_tmpfile=/var/tmp/$ns_arg0.$$
ns_amqpconfig=/opt/smartdc/agents/bin/amqp-config
ns_root="$(getprop caconfig/path-dist)"
ns_node="$(getprop caconfig/path-node)"
ns_logbase="$(getprop caconfig/path-logs)"
ns_rt=$(getprop caconfig/run-rt)
ns_name=
ns_args=

#
# Set up log files and directories
#
mkdir -p "$ns_logbase/$ns_name" || fail "failed to create log directory"
ns_dbglogfile="$ns_logbase/$ns_name/amqp-$(date +%F.%T).$$"
ns_rqlogfile="$ns_logbase/$ns_name/requests-$(date +%F.%T).$$"

#
# Figure out which service to start.
#
case $SMF_FMRI in
	*caconfigsvc*)	ns_name=caconfigsvc
			load_mapi
			ns_args="$ns_dbglogfile $ns_rqlogfile"
			;;
	*caaggsvc*)	export HOST=$(uname -n)-${SMF_FMRI/*:}
			ns_name=caaggsvc
			load_geoip
			ns_args="$ns_dbglogfile"
			;;
	*cainstsvc*)	ns_name=cainstsvc
			load_dtracepath
			ns_args="$ns_dbglogfile"
			;;
	*castashsvc*)	ns_name=castashsvc
			stash=$(getprop caconfig/stash-rootdir)
			[[ -n $stash ]] || fail "no stash configured"
			echo "using stash '$stash'"
			ns_args="$stash $ns_dbglogfile"
			;;
	*) 		fail "don't know how to start $SMF_FMRI" ;;
esac

cd "$ns_root" || fail "failed to cd"
ns_root=$(pwd)
ns_exec=cmd/$ns_name.js
[[ -f $ns_exec ]] || fail "couldn't find $ns_exec"
[[ -x $ns_node ]] || fail "couldn't find executable node"

load_amqp || fail "failed to load amqp config"
load_nodepath || fail "failed to load node path"
env | sort | egrep '^(AMQP_|MAPI_|NODE_PATH)' | grep -v PASSWORD

#
# Launch the daemon.
#
smf_clear_env
$ns_node $ns_exec $ns_args &
ns_pid=$!
[[ $ns_rt == "true" ]] && run_realtime $ns_pid
exit $SMF_EXIT_OK
