/*
 * heap-dbg-inl.h: auto-generated.  Do not edit directly.
 * See heap-dbg-common.h for details.
 */

#ifndef HEAPDBG_CONSTANTS_H
#define HEAPDBG_CONSTANTS_H

#include "heap-dbg-common.h"

/* HeapObject class constants */
#define	V8_OFF_HEAPOBJECT_MAP	(V8_OFF_HEAP(0x0))

/* String class constants */
#define	V8_OFF_STRING_LENGTH	(V8_OFF_HEAP(0x4))

/* TemplateInfo class constants */
#define	V8_OFF_TEMPLATEINFO_TAG	(V8_OFF_HEAP(0x4))
#define	V8_OFF_TEMPLATEINFO_PROPERTY_LIST	(V8_OFF_HEAP(0x8))

/* Code class constants */
#define	V8_OFF_CODE_RELOCATION_INFO	(V8_OFF_HEAP(0x8))
#define	V8_OFF_CODE_DEOPTIMIZATION_DATA	(V8_OFF_HEAP(0xc))

/* FixedArray class constants */
#define	V8_OFF_FIXEDARRAY_LENGTH	(V8_OFF_HEAP(0x4))
#define	V8_OFF_FIXEDARRAY_DATA	(V8_OFF_HEAP(0x8))

/* CallHandlerInfo class constants */
#define	V8_OFF_CALLHANDLERINFO_CALLBACK	(V8_OFF_HEAP(0x4))
#define	V8_OFF_CALLHANDLERINFO_DATA	(V8_OFF_HEAP(0x8))

/* ObjectTemplateInfo class constants */
#define	V8_OFF_OBJECTTEMPLATEINFO_CONSTRUCTOR	(V8_OFF_HEAP(0xc))
#define	V8_OFF_OBJECTTEMPLATEINFO_INTERNAL_FIELD_COUNT	(V8_OFF_HEAP(0x10))

/* InterceptorInfo class constants */
#define	V8_OFF_INTERCEPTORINFO_GETTER	(V8_OFF_HEAP(0x4))
#define	V8_OFF_INTERCEPTORINFO_SETTER	(V8_OFF_HEAP(0x8))
#define	V8_OFF_INTERCEPTORINFO_QUERY	(V8_OFF_HEAP(0xc))
#define	V8_OFF_INTERCEPTORINFO_DELETER	(V8_OFF_HEAP(0x10))
#define	V8_OFF_INTERCEPTORINFO_ENUMERATOR	(V8_OFF_HEAP(0x14))
#define	V8_OFF_INTERCEPTORINFO_DATA	(V8_OFF_HEAP(0x18))

/* JSRegExp class constants */
#define	V8_OFF_JSREGEXP_DATA	(V8_OFF_HEAP(0xc))

/* JSValue class constants */
#define	V8_OFF_JSVALUE_VALUE	(V8_OFF_HEAP(0xc))

/* ByteArray class constants */
#define	V8_OFF_BYTEARRAY_LENGTH	(V8_OFF_HEAP(0x4))

/* CodeCache class constants */
#define	V8_OFF_CODECACHE_DEFAULT_CACHE	(V8_OFF_HEAP(0x4))
#define	V8_OFF_CODECACHE_NORMAL_TYPE_CACHE	(V8_OFF_HEAP(0x8))

/* GlobalObject class constants */
#define	V8_OFF_GLOBALOBJECT_BUILTINS	(V8_OFF_HEAP(0xc))
#define	V8_OFF_GLOBALOBJECT_GLOBAL_CONTEXT	(V8_OFF_HEAP(0x10))
#define	V8_OFF_GLOBALOBJECT_GLOBAL_RECEIVER	(V8_OFF_HEAP(0x14))

/* SeqAsciiString class constants */
#define	V8_OFF_SEQASCIISTRING_CHARS	(V8_OFF_HEAP(0xc))

/* JSArray class constants */
#define	V8_OFF_JSARRAY_LENGTH	(V8_OFF_HEAP(0xc))

/* Oddball class constants */
#define	V8_OFF_ODDBALL_TO_STRING	(V8_OFF_HEAP(0x4))
#define	V8_OFF_ODDBALL_TO_NUMBER	(V8_OFF_HEAP(0x8))

/* ConsString class constants */
#define	V8_OFF_CONSSTRING_FIRST	(V8_OFF_HEAP(0xc))
#define	V8_OFF_CONSSTRING_SECOND	(V8_OFF_HEAP(0x10))

/* JSFunction class constants */
#define	V8_OFF_JSFUNCTION_PROTOTYPE_OR_INITIAL_MAP	(V8_OFF_HEAP(0x10))
#define	V8_OFF_JSFUNCTION_SHARED	(V8_OFF_HEAP(0x14))
#define	V8_OFF_JSFUNCTION_LITERALS	(V8_OFF_HEAP(0x1c))
#define	V8_OFF_JSFUNCTION_NEXT_FUNCTION_LINK	(V8_OFF_HEAP(0x20))

/* TypeSwitchInfo class constants */
#define	V8_OFF_TYPESWITCHINFO_TYPES	(V8_OFF_HEAP(0x4))

/* DebugInfo class constants */
#define	V8_OFF_DEBUGINFO_SHARED	(V8_OFF_HEAP(0x4))
#define	V8_OFF_DEBUGINFO_ORIGINAL_CODE	(V8_OFF_HEAP(0x8))
#define	V8_OFF_DEBUGINFO_CODE	(V8_OFF_HEAP(0xc))
#define	V8_OFF_DEBUGINFO_BREAK_POINTS	(V8_OFF_HEAP(0x14))

/* ExternalString class constants */
#define	V8_OFF_EXTERNALSTRING_RESOURCE	(V8_OFF_HEAP(0xc))

/* AccessorInfo class constants */
#define	V8_OFF_ACCESSORINFO_GETTER	(V8_OFF_HEAP(0x4))
#define	V8_OFF_ACCESSORINFO_SETTER	(V8_OFF_HEAP(0x8))
#define	V8_OFF_ACCESSORINFO_DATA	(V8_OFF_HEAP(0xc))
#define	V8_OFF_ACCESSORINFO_NAME	(V8_OFF_HEAP(0x10))
#define	V8_OFF_ACCESSORINFO_FLAG	(V8_OFF_HEAP(0x14))

/* SignatureInfo class constants */
#define	V8_OFF_SIGNATUREINFO_RECEIVER	(V8_OFF_HEAP(0x4))
#define	V8_OFF_SIGNATUREINFO_ARGS	(V8_OFF_HEAP(0x8))

/* Script class constants */
#define	V8_OFF_SCRIPT_SOURCE	(V8_OFF_HEAP(0x4))
#define	V8_OFF_SCRIPT_NAME	(V8_OFF_HEAP(0x8))
#define	V8_OFF_SCRIPT_LINE_OFFSET	(V8_OFF_HEAP(0xc))
#define	V8_OFF_SCRIPT_COLUMN_OFFSET	(V8_OFF_HEAP(0x10))
#define	V8_OFF_SCRIPT_DATA	(V8_OFF_HEAP(0x14))
#define	V8_OFF_SCRIPT_CONTEXT_DATA	(V8_OFF_HEAP(0x18))
#define	V8_OFF_SCRIPT_WRAPPER	(V8_OFF_HEAP(0x1c))
#define	V8_OFF_SCRIPT_TYPE	(V8_OFF_HEAP(0x20))
#define	V8_OFF_SCRIPT_COMPILATION_TYPE	(V8_OFF_HEAP(0x24))
#define	V8_OFF_SCRIPT_LINE_ENDS	(V8_OFF_HEAP(0x28))
#define	V8_OFF_SCRIPT_ID	(V8_OFF_HEAP(0x2c))
#define	V8_OFF_SCRIPT_EVAL_FROM_SHARED	(V8_OFF_HEAP(0x30))
#define	V8_OFF_SCRIPT_EVAL_FROM_INSTRUCTIONS_OFFSET	(V8_OFF_HEAP(0x34))

/* BreakPointInfo class constants */
#define	V8_OFF_BREAKPOINTINFO_CODE_POSITION	(V8_OFF_HEAP(0x4))
#define	V8_OFF_BREAKPOINTINFO_SOURCE_POSITION	(V8_OFF_HEAP(0x8))
#define	V8_OFF_BREAKPOINTINFO_STATEMENT_POSITION	(V8_OFF_HEAP(0xc))
#define	V8_OFF_BREAKPOINTINFO_BREAK_POINT_OBJECTS	(V8_OFF_HEAP(0x10))

/* JSObject class constants */
#define	V8_OFF_JSOBJECT_PROPERTIES	(V8_OFF_HEAP(0x4))
#define	V8_OFF_JSOBJECT_ELEMENTS	(V8_OFF_HEAP(0x8))

/* Map class constants */
#define	V8_OFF_MAP_INSTANCE_ATTRIBUTES	(V8_OFF_HEAP(0x8))
#define	V8_OFF_MAP_CONSTRUCTOR	(V8_OFF_HEAP(0x10))
#define	V8_OFF_MAP_INSTANCE_DESCRIPTORS	(V8_OFF_HEAP(0x14))
#define	V8_OFF_MAP_CODE_CACHE	(V8_OFF_HEAP(0x18))

/* AccessCheckInfo class constants */
#define	V8_OFF_ACCESSCHECKINFO_NAMED_CALLBACK	(V8_OFF_HEAP(0x4))
#define	V8_OFF_ACCESSCHECKINFO_INDEXED_CALLBACK	(V8_OFF_HEAP(0x8))
#define	V8_OFF_ACCESSCHECKINFO_DATA	(V8_OFF_HEAP(0xc))

/* JSMessageObject class constants */
#define	V8_OFF_JSMESSAGEOBJECT_TYPE	(V8_OFF_HEAP(0xc))
#define	V8_OFF_JSMESSAGEOBJECT_ARGUMENTS	(V8_OFF_HEAP(0x10))
#define	V8_OFF_JSMESSAGEOBJECT_SCRIPT	(V8_OFF_HEAP(0x14))
#define	V8_OFF_JSMESSAGEOBJECT_STACK_TRACE	(V8_OFF_HEAP(0x18))
#define	V8_OFF_JSMESSAGEOBJECT_STACK_FRAMES	(V8_OFF_HEAP(0x1c))
#define	V8_OFF_JSMESSAGEOBJECT_START_POSITION	(V8_OFF_HEAP(0x20))
#define	V8_OFF_JSMESSAGEOBJECT_END_POSITION	(V8_OFF_HEAP(0x24))

/* FunctionTemplateInfo class constants */
#define	V8_OFF_FUNCTIONTEMPLATEINFO_SERIAL_NUMBER	(V8_OFF_HEAP(0xc))
#define	V8_OFF_FUNCTIONTEMPLATEINFO_CALL_CODE	(V8_OFF_HEAP(0x10))
#define	V8_OFF_FUNCTIONTEMPLATEINFO_PROPERTY_ACCESSORS	(V8_OFF_HEAP(0x14))
#define	V8_OFF_FUNCTIONTEMPLATEINFO_PROTOTYPE_TEMPLATE	(V8_OFF_HEAP(0x18))
#define	V8_OFF_FUNCTIONTEMPLATEINFO_PARENT_TEMPLATE	(V8_OFF_HEAP(0x1c))
#define	V8_OFF_FUNCTIONTEMPLATEINFO_NAMED_PROPERTY_HANDLER	(V8_OFF_HEAP(0x20))
#define	V8_OFF_FUNCTIONTEMPLATEINFO_INDEXED_PROPERTY_HANDLER	(V8_OFF_HEAP(0x24))
#define	V8_OFF_FUNCTIONTEMPLATEINFO_INSTANCE_TEMPLATE	(V8_OFF_HEAP(0x28))
#define	V8_OFF_FUNCTIONTEMPLATEINFO_CLASS_NAME	(V8_OFF_HEAP(0x2c))
#define	V8_OFF_FUNCTIONTEMPLATEINFO_SIGNATURE	(V8_OFF_HEAP(0x30))
#define	V8_OFF_FUNCTIONTEMPLATEINFO_INSTANCE_CALL_HANDLER	(V8_OFF_HEAP(0x34))
#define	V8_OFF_FUNCTIONTEMPLATEINFO_ACCESS_CHECK_INFO	(V8_OFF_HEAP(0x38))
#define	V8_OFF_FUNCTIONTEMPLATEINFO_FLAG	(V8_OFF_HEAP(0x3c))

/* JSGlobalProxy class constants */
#define	V8_OFF_JSGLOBALPROXY_CONTEXT	(V8_OFF_HEAP(0xc))

/* SharedFunctionInfo class constants */
#define	V8_OFF_SHAREDFUNCTIONINFO_NAME	(V8_OFF_HEAP(0x4))
#define	V8_OFF_SHAREDFUNCTIONINFO_CONSTRUCT_STUB	(V8_OFF_HEAP(0x10))
#define	V8_OFF_SHAREDFUNCTIONINFO_INSTANCE_CLASS_NAME	(V8_OFF_HEAP(0x14))
#define	V8_OFF_SHAREDFUNCTIONINFO_FUNCTION_DATA	(V8_OFF_HEAP(0x18))
#define	V8_OFF_SHAREDFUNCTIONINFO_SCRIPT	(V8_OFF_HEAP(0x1c))
#define	V8_OFF_SHAREDFUNCTIONINFO_DEBUG_INFO	(V8_OFF_HEAP(0x20))
#define	V8_OFF_SHAREDFUNCTIONINFO_INFERRED_NAME	(V8_OFF_HEAP(0x24))
#define	V8_OFF_SHAREDFUNCTIONINFO_INITIAL_MAP	(V8_OFF_HEAP(0x28))
#define	V8_OFF_SHAREDFUNCTIONINFO_THIS_PROPERTY_ASSIGNMENTS	(V8_OFF_HEAP(0x2c))
#define	V8_OFF_SHAREDFUNCTIONINFO_LENGTH	(V8_OFF_HEAP(0x34))
#define	V8_OFF_SHAREDFUNCTIONINFO_FORMAL_PARAMETER_COUNT	(V8_OFF_HEAP(0x38))
#define	V8_OFF_SHAREDFUNCTIONINFO_EXPECTED_NOF_PROPERTIES	(V8_OFF_HEAP(0x3c))
#define	V8_OFF_SHAREDFUNCTIONINFO_NUM_LITERALS	(V8_OFF_HEAP(0x40))
#define	V8_OFF_SHAREDFUNCTIONINFO_START_POSITION_AND_TYPE	(V8_OFF_HEAP(0x44))
#define	V8_OFF_SHAREDFUNCTIONINFO_END_POSITION	(V8_OFF_HEAP(0x48))
#define	V8_OFF_SHAREDFUNCTIONINFO_FUNCTION_TOKEN_POSITION	(V8_OFF_HEAP(0x4c))
#define	V8_OFF_SHAREDFUNCTIONINFO_COMPILER_HINTS	(V8_OFF_HEAP(0x50))
#define	V8_OFF_SHAREDFUNCTIONINFO_THIS_PROPERTY_ASSIGNMENTS_COUNT	(V8_OFF_HEAP(0x54))
#define	V8_OFF_SHAREDFUNCTIONINFO_OPT_COUNT	(V8_OFF_HEAP(0x58))

/* offsets from "roots_" for special values */
#define	V8_OFF_ROOTS_VALUE_UNDEFINED	0x4
#define	V8_OFF_ROOTS_VALUE_NULL	0x6
#define	V8_OFF_ROOTS_VALUE_TRUE	0x7
#define	V8_OFF_ROOTS_VALUE_FALSE	0x8
#define	V8_OFF_ROOTS_VALUE_NAN	0x34
#define	V8_OFF_ROOTS_VALUE_MINZERO	0x35

/* offsets for object identification */
#define	V8_FirstNonstringType	0x80
#define	V8_IsNotStringMask	0x80
#define	V8_StringTag	0x0
#define	V8_NotStringTag	0x80
#define	V8_StringEncodingMask	0x4
#define	V8_TwoByteStringTag	0x0
#define	V8_AsciiStringTag	0x4
#define	V8_StringRepresentationMask	0x3
#define	V8_SeqStringTag	0x0
#define	V8_ConsStringTag	0x1
#define	V8_ExternalStringTag	0x2
#define	V8_FailureTag	0x3
#define	V8_FailureTagMask	0x3
#define	V8_HeapObjectTag	0x1
#define	V8_HeapObjectTagMask	0x3
#define	V8_SmiTag	0x0
#define	V8_SmiTagMask	0x1
#define	V8_SmiValueShift	0x1
#define	V8_OFF_FP_MARKER	0xfffffff8
#define	V8_OFF_FP_FUNCTION	0xfffffff8

#endif
