#!/bin/bash
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

#
# Copyright (c) 2014, Joyent, Inc.
#

#
# Tag and branch the cloud-analytics repo for an official release.
#

function fail
{
	echo "$*" >&2
	exit 1
}

b_arg0=$(basename $0)
b_tmpdir=/var/tmp/$b_arg0.$$
b_repos=cloud-analytics
b_release=$(date +%Y%m%d)
b_tag=$b_release
b_branch=release-$b_release

echo -n "Creating temporary directory $b_tmpdir ... "
mkdir -p $b_tmpdir || fail "failed"
echo "done."

cd $b_tmpdir

for repo in $b_repos; do
	echo -n "Cloning repo $repo ... "
	git clone -q git@git.joyent.com:$repo.git || fail "failed"
	echo "done."

	cd $repo

	echo -n "Tagging repo with '$b_tag' ... "
	git tag -a $b_tag -m "$b_tag release" > /dev/null || \
	    fail "git tag failed"
	git push -q --tags || fail "git push --tags failed"
	echo "done."

	echo -n "Creating local branch $b_branch ... "
	git checkout -b $b_branch > /dev/null || fail "failed"
	echo "done."

	echo -n "Pushing to remote branch $b_branch ... "
	git push -q origin $b_branch || fail "failed"
	echo "done."
done
