#!/bin/bash

#
# deploy: deploys services to a specified system
#
shopt -s xpg_echo

function fail
{
	echo "$*" >&2
	exit 1
}

function usage
{
	echo "$d_arg0: $*" >&2
	cat <<-USAGE >&2
Usage: $d_arg0 [-r] -h host -s svc [-s svc ...]

Deploy the named service(s) to the specified host.

    -r	Remove old contents first
    -h	Hostname to deploy to
    -s	Service to deploy; one or more of
    	    agg (aggregator service)
    	    cfg (configuration service)
    	    inst (instrumenter service)
USAGE
	exit 2
}

d_arg0=$(basename $0)
d_svcs=
d_tmpbase=/var/tmp/$d_arg0.$$
d_wsroot=

while getopts ":s:h:r" c; do
	case "$c" in
	r)	eval opt_$c=true				;;
	h)	eval opt_$c="$OPTARG"				;;
	s)	d_svcs="$d_svcs $OPTARG"			;;
	:)	usage "option requires an argument -- $OPTARG"	;;
	*)	usage "illegal option -- $OPTARG"		;;
	esac
done

[[ -n $d_svcs ]] || usage "-s is required"
[[ -n $opt_h ]] || usage "-h is required"

cd $(dirname $0)
d_base=$(pwd)/../build/pkg
cd -

d_fmris=cabase
d_tgzs=$d_base/cabase.tar.gz
for svc in $d_svcs; do
	case $svc in
	agg|caaggsvc)
		d_fmris="$d_fmris caaggsvc"
		d_tgzs="$d_tgzs $d_base/caaggsvc.tar.gz"
		;;
	cfg|config|caconfig|caconfigsvc)
		d_fmris="$d_fmris caconfigsvc"
		d_tgzs="$d_tgzs $d_base/caconfigsvc.tar.gz"
		;;
	inst|cainst|cainstsvc)
		d_fmris="$d_fmris cainstsvc"
		d_tgzs="$d_tgzs $d_base/cainstsvc.tar.gz"
		;;
	*)
		usage "illegal service: $svc"
		;;
	esac
done

d_rdeploy=${d_tmpbase}_deploy.sh
r_rdeploy=$d_arg0.$$_deploy.sh

cat > $d_rdeploy << REMOTE_DEPLOY
#!/bin/bash

shopt -s xpg_echo

#
# By default use the version of npm in your path, unless this specific version
# exists.
#
r_npm=npm
[[ -x /opt/smartdc/agents/bin/agents-npm ]] && \
    r_npm=/opt/smartdc/agents/bin/agents-npm
[[ -x /opt/local/bin/npm ]] && \
    r_npm=/opt/local/bin/npm

function fail
{
	echo "\$*" >&2
	exit 1
}

[[ ! -x "\$r_npm" ]] && fail "Missing npm"

r_svcs=\$(svcs -H -ofmri '*/ca/*')
for svc in \$r_svcs; do
	echo "Disabling \$svc ... \c"
	svcadm disable -s \$svc || fail "failed"
	echo "done."
done

REMOTE_DEPLOY

#
# XXX should use versioning to avoid changing live stuff
#
if [[ $opt_r = true ]]; then
cat >> $d_rdeploy << REMOTE_DEPLOY
echo "Removing old contents from /opt/smartdc/ca ... \c"
rm -rf /opt/smartdc/ca || fail "failed"
echo "done."
REMOTE_DEPLOY
fi

cat >> $d_rdeploy << REMOTE_DEPLOY
cd /
for svc in $d_fmris; do
	echo "Installing service \$svc ... \c"
	\$r_npm install $d_tmpbase/\$svc.tar.gz || fail "can't npm install $svc"
done

echo "Removing tarball and script ... \c"
rm -f $d_tmpbase/$r_rdeploy
for tgz in $d_fmris; do
	rm -f $d_tmpbase/\$tgz.tar.gz
done
rmdir $d_tmpbase

r_svcs=\$(svcs -H -ofmri '*/ca/*')
for svc in \$r_svcs; do
	echo "Enabling \$svc ... \c"
	svcadm enable -s \$svc || fail "failed"
	echo "done."
done

echo "done."
REMOTE_DEPLOY

echo "Making remote temporary directory (may prompt for root password)"
ssh root@$opt_h mkdir $d_tmpbase || fail "failed"
echo "Copying script and packages to root@$opt_h via scp (may prompt for root password twice)"
scp $d_rdeploy $d_tgzs root@$opt_h:$d_tmpbase || fail "failed"

echo "Invoking remote script (may prompt again)."
ssh root@$opt_h bash $d_tmpbase/$r_rdeploy || fail "failed"

echo "Removing local tarball and script ... \c"
rm -f $d_rdeploy
echo "done."
