#!/bin/bash

#
# cadeploy-local: deploys services to current system
#
shopt -s xpg_echo

function fail
{
	echo "$*" >&2
	exit 1
}

dl_arg0=$(basename $0)
cd $(dirname $0)/../smf/manifest

echo "Validating services ... \c"
for svc in $@; do
	[[ -f smartdc-ca-$svc.xml ]] || fail "illegal service: $svc"
done
echo "done."

for svc in $@; do
	echo "Importing manifest for $svc ... \c"
	svccfg import smartdc-ca-$svc.xml || fail "failed"
	echo "done."
done

for svc in $@; do
	echo "Enabling $svc ... \c"
	svcadm enable -rs smartdc/ca/$svc > /dev/null 2>&1 || fail "failed"
	echo "done."
done
