#!/bin/bash

#
# npath: determine NODE_PATH and print it out for use by different utilities
#

#
# Find the root of the workspace assuming a fixed relative path to this script.
#
ws_arg0="$(dirname $0)"
cd "$ws_arg0/.."
ws_root=$(pwd)
cd - > /dev/null

#
# For each subdir under deps', add it to NODE_PATH.  This isn't pretty but it
# gets the job done.
#

for dir in $ws_root/deps/*; do
	mod=$(basename $dir)
	export NODE_PATH="$NODE_PATH:$ws_root/deps/$mod"
	export NODE_PATH="$NODE_PATH:$ws_root/deps/$mod/build/default"
done

export NODE_PATH="$NODE_PATH:$ws_root/deps/connect/lib"
export NODE_PATH="$NODE_PATH:$ws_root/deps/node-heatmap/lib"

echo "NODE_PATH=$NODE_PATH"

[[ -z $AMQP_HOST ]] && echo AMQP_HOST=10.99.99.5
[[ -z $GEOIP_DATABASE ]] && \
    echo GEOIP_DATABASE=/opt/local/share/GeoIP/GeoLiteCity.dat
