#!/bin/bash

#
# ws: set up NODE_PATH for use in this workspace
#

#
# Find the root of the workspace assuming a fixed relative path to this script.
#
ws_arg0="$(dirname $0)"
cd "$ws_arg0/.."
ws_root=$(pwd)
cd - > /dev/null

#
# For each subdir under 'lib' and 'deps', add it to NODE_PATH.  This isn't
# pretty but it gets the job done.
#
for dir in $ws_root/lib/*; do
	export NODE_PATH="$NODE_PATH:$ws_root/lib/$(basename $dir)"
done

for dir in $ws_root/deps/*; do
	mod=$(basename $dir)
	export NODE_PATH="$NODE_PATH:$ws_root/deps/$mod"
	[[ -d $ws_root/deps/$mod/build/default ]] &&
		export NODE_PATH="$NODE_PATH:$ws_root/deps/$mod/build/default"
done

export NODE_PATH="$NODE_PATH:$ws_root/deps/connect/lib"
export NODE_PATH="$NODE_PATH:$ws_root/deps/node-heatmap/lib"

echo "NODE_PATH=$NODE_PATH"
exec $SHELL
