#!/bin/bash
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

#
# Copyright (c) 2014, Joyent, Inc.
#

#
# ws: set up NODE_PATH for use in this workspace
#

cd $(dirname $0)
export $(./npath)
export AMQP_HOST=10.99.99.12	# only used for COAL
export PATH=$PWD/../deps/node:$PWD/../deps/ctf2json:$PATH
export SRC=$PWD/../
cd - > /dev/null
exec $SHELL
